/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.vistasAdmin;

import bbdd.ConsultasProducto;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Producto;
import utilidades.Utilidades;
import vistas.VentanaLogin;


/**
 * Ventana modal encargada de registrar nuevos artículos en el sistema.
 * Implementa la interfaz gráfica para la introducción de datos del producto, delegando la carga de listas desplegables y la persistencia de datos a la capa de modelo - BBDD.
 * 
 * @author Jose y Patricia
 * @version 1.0
 * @since 2026
 */
public class RegistrarArticulo extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarArticulo.class.getName());

    /**
     * Constructor principal de la ventana "Registrar Articulo".
     * Inicializa los componentes visuales, aplica la identidad corporativa, carga dinámicamente los datos de los desplegables y muestra la información de sesión activa.
     */
    public RegistrarArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);
        
        // Nada más abrir la ventana ya sale la sugerencia del Codigo Producto para llevar un orden
        String sugerenciaCodigoProducto = ConsultasProducto.generarSiguienteCodigoProducto();
        campoCodigo.setText(sugerenciaCodigoProducto);
        campoCodigo.setEditable(false); // Bloqueado: Para que el usuario no lo cambie, no es requisito pero lo hemos decidido así para mejor funcionalidad
        
        // Cargar Combos 
        cargarCombosArticulos();
        
        // Rescatar fecha y hora en la interfaz
        LocalDateTime fechaHora = LocalDateTime.now();
        lblRescataFechayHora.setText("Admin activo — "
                + fechaHora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));

        // Rescata Administrador:
        lblImprimirAdmin.setText(VentanaLogin.user);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        panelSecundario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonRegistrarUsuario = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        comboOrigen = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        campoCodigo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoDescripcionArticulo = new javax.swing.JTextArea();
        panelSecundario1 = new javax.swing.JPanel();
        lblUsuario1 = new javax.swing.JLabel();
        lblTipo1 = new javax.swing.JLabel();
        comboOferta = new javax.swing.JComboBox<>();
        lblNombre1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        campoPrecioVenta = new javax.swing.JTextField();
        comboDestacado = new javax.swing.JComboBox<>();
        campoPrecioCompra = new javax.swing.JTextField();
        campoStock = new javax.swing.JTextField();
        lblTienda2 = new javax.swing.JLabel();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        botonRegistrarArticulo = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblImprimirAdmin = new javax.swing.JLabel();
        lblUsuario2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA REGISTRAR ARTÍCULO");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(3, 32, 38));

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo.setText("Registrar Artículo");

        lblSubtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo.setText("Nuevo producto en inventario");

        jToolBar1.setBackground(new java.awt.Color(191, 150, 99));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(2, 2));
        jToolBar1.setMinimumSize(new java.awt.Dimension(2, 2));

        panelSecundario.setBackground(new java.awt.Color(9, 48, 64));
        panelSecundario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblUsuario.setBackground(new java.awt.Color(191, 150, 99));
        lblUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Nombre");
        lblUsuario.setOpaque(true);

        botonCancelar.setBackground(new java.awt.Color(3, 32, 38));
        botonCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(191, 150, 99));
        botonCancelar.setText("Cancelar");
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRegistrarUsuario.setBackground(new java.awt.Color(191, 150, 99));
        botonRegistrarUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonRegistrarUsuario.setText("Registrar");
        botonRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTipo.setBackground(new java.awt.Color(112, 137, 140));
        lblTipo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Categoría");
        lblTipo.setOpaque(true);

        comboOrigen.setBackground(new java.awt.Color(3, 32, 38));
        comboOrigen.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboOrigen.setForeground(new java.awt.Color(112, 137, 140));
        comboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboOrigen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboOrigen.setName("Orígen"); // NOI18N

        lblNombre.setBackground(new java.awt.Color(191, 150, 99));
        lblNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Código");
        lblNombre.setOpaque(true);

        lblEstado.setBackground(new java.awt.Color(112, 137, 140));
        lblEstado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Origen");
        lblEstado.setOpaque(true);

        lblFecha.setBackground(new java.awt.Color(191, 182, 158));
        lblFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Descripción");
        lblFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFecha.setOpaque(true);

        campoNombre.setBackground(new java.awt.Color(3, 32, 38));
        campoNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(112, 137, 140));
        campoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoNombre.setName("Nombre"); // NOI18N

        comboCategoria.setBackground(new java.awt.Color(3, 32, 38));
        comboCategoria.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboCategoria.setForeground(new java.awt.Color(112, 137, 140));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboCategoria.setName("Categoría"); // NOI18N

        campoCodigo.setBackground(new java.awt.Color(3, 32, 38));
        campoCodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoCodigo.setForeground(new java.awt.Color(112, 137, 140));
        campoCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoCodigo.setName("Código"); // NOI18N

        campoDescripcionArticulo.setBackground(new java.awt.Color(3, 32, 38));
        campoDescripcionArticulo.setColumns(20);
        campoDescripcionArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoDescripcionArticulo.setForeground(new java.awt.Color(112, 137, 140));
        campoDescripcionArticulo.setLineWrap(true);
        campoDescripcionArticulo.setRows(5);
        campoDescripcionArticulo.setWrapStyleWord(true);
        campoDescripcionArticulo.setAutoscrolls(false);
        campoDescripcionArticulo.setName("Descripción"); // NOI18N
        jScrollPane4.setViewportView(campoDescripcionArticulo);

        javax.swing.GroupLayout panelSecundarioLayout = new javax.swing.GroupLayout(panelSecundario);
        panelSecundario.setLayout(panelSecundarioLayout);
        panelSecundarioLayout.setHorizontalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundarioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSecundarioLayout.createSequentialGroup()
                        .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSecundarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(panelSecundarioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(comboOrigen, 0, 225, Short.MAX_VALUE)
                            .addComponent(comboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoNombre)
                            .addComponent(campoCodigo))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelSecundarioLayout.setVerticalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSecundarioLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        panelSecundario1.setBackground(new java.awt.Color(9, 48, 64));
        panelSecundario1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblUsuario1.setBackground(new java.awt.Color(191, 150, 99));
        lblUsuario1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario1.setText("Precio Venta");
        lblUsuario1.setOpaque(true);

        lblTipo1.setBackground(new java.awt.Color(112, 137, 140));
        lblTipo1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblTipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo1.setText("Stock");
        lblTipo1.setOpaque(true);

        comboOferta.setBackground(new java.awt.Color(3, 32, 38));
        comboOferta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboOferta.setForeground(new java.awt.Color(112, 137, 140));
        comboOferta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboOferta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboOferta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboOferta.setName("Oferta"); // NOI18N

        lblNombre1.setBackground(new java.awt.Color(191, 150, 99));
        lblNombre1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre1.setText("Precio Compra");
        lblNombre1.setOpaque(true);

        lblEstado1.setBackground(new java.awt.Color(191, 182, 158));
        lblEstado1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblEstado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado1.setText("Destacado");
        lblEstado1.setOpaque(true);

        campoPrecioVenta.setEditable(false);
        campoPrecioVenta.setBackground(new java.awt.Color(3, 32, 38));
        campoPrecioVenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPrecioVenta.setForeground(new java.awt.Color(112, 137, 140));
        campoPrecioVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPrecioVenta.setName("Precio Venta"); // NOI18N

        comboDestacado.setBackground(new java.awt.Color(3, 32, 38));
        comboDestacado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboDestacado.setForeground(new java.awt.Color(112, 137, 140));
        comboDestacado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboDestacado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboDestacado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboDestacado.setName("Destacado"); // NOI18N

        campoPrecioCompra.setBackground(new java.awt.Color(3, 32, 38));
        campoPrecioCompra.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPrecioCompra.setForeground(new java.awt.Color(112, 137, 140));
        campoPrecioCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPrecioCompra.setName("Precio Compra"); // NOI18N
        campoPrecioCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPrecioCompraFocusLost(evt);
            }
        });
        campoPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioCompraActionPerformed(evt);
            }
        });

        campoStock.setBackground(new java.awt.Color(3, 32, 38));
        campoStock.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoStock.setForeground(new java.awt.Color(112, 137, 140));
        campoStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoStock.setName("Stock"); // NOI18N

        lblTienda2.setBackground(new java.awt.Color(191, 182, 158));
        lblTienda2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblTienda2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTienda2.setText("Oferta");
        lblTienda2.setOpaque(true);

        panelFinal.setBackground(new java.awt.Color(9, 48, 64));
        panelFinal.setForeground(new java.awt.Color(191, 150, 99));
        panelFinal.setOpaque(false);

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(3, 32, 38));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSistemaGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelSecundario1Layout = new javax.swing.GroupLayout(panelSecundario1);
        panelSecundario1.setLayout(panelSecundario1Layout);
        panelSecundario1Layout.setHorizontalGroup(
            panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundario1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTipo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstado1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTienda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboOferta, 0, 225, Short.MAX_VALUE)
                    .addComponent(comboDestacado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoStock)
                    .addComponent(campoPrecioVenta)
                    .addComponent(campoPrecioCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundario1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSecundario1Layout.setVerticalGroup(
            panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundario1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDestacado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSecundario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTienda2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        botonRegistrarArticulo.setBackground(new java.awt.Color(191, 150, 99));
        botonRegistrarArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonRegistrarArticulo.setText("Registrar");
        botonRegistrarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarArticuloActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(3, 32, 38));
        botonSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(191, 150, 99));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.setLabel("Volver");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(3, 32, 38));

        lblImprimirAdmin.setBackground(new java.awt.Color(9, 48, 64));
        lblImprimirAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblImprimirAdmin.setForeground(new java.awt.Color(191, 150, 99));
        lblImprimirAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUsuario2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario2.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario2)
                    .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitulo)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(panelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addComponent(panelSecundario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addGap(12, 12, 12)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelSecundario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 323, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));

        menuArchivo.setText("Archivo");
        menuArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuArchivo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemCerrar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemCerrar.setText("Cerrar");
        itemCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCerrar);

        jMenuBar1.add(menuArchivo);

        menuAyuda.setText("Ayuda");
        menuAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAyuda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemAcercaDe.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        utilidades.Utilidades.mostrarAcercaDe(this);
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRegistrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarArticuloActionPerformed
        registrarArticulo();
    }//GEN-LAST:event_botonRegistrarArticuloActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed
    /**
     * Gestiona el evento de pérdida de foco en el precio de compra.
     * Calcula automáticamente el Precio de Venta aplicando un margen del 30% y un IVA del 21% sobre el precio de adquisición.
     * @param evt El evento de foco (FocusEvent) que dispara la acción al salir del componente.
     */
    private void campoPrecioCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPrecioCompraFocusLost
       
        // ** Evento FocusLost ** //
        
        // Evento que se activa justo en cuanto el usuario sale de el, en este caso tras ingresar la cantidad en Precio Compra
        // Y nos ejecuta:
        
        try {

            // Rescatamos el texto y Cambiamos la coma por punto antes de calcular por si nos pusieran coma ya que no nos la cogeria
            String numeroConPunto = campoPrecioCompra.getText().trim().replace(',', '.'); // Doblemente blindando

            // Rescatamos el precio de compra
            double precioCompra = Double.parseDouble(numeroConPunto);

            // Cálculo: Incremento 30% y luego añadir 21% de IVA
            // Matemáticamente es: Compra * 1.30 (margen) * 1.21 (IVA)
            double precioVentaSinIncremento = precioCompra * 1.30 * 1.21; // El incremento se calcula en esta sola línea 

            // Redondeo otra vez a 2 decimales:
            double precioVentaAplicado = Math.round(precioVentaSinIncremento * 100.0) / 100.0;

            // Lo ponemos en el campo de Precio Venta formateado con 2 decimales
            campoPrecioVenta.setText(utilidades.Utilidades.formatoDosDecimales(precioVentaAplicado));

            // También formateamos el de compra para que quede bonito
            campoPrecioCompra.setText(utilidades.Utilidades.formatoDosDecimales(precioCompra));

        } catch (NumberFormatException e) { 
            
            System.err.println("Error en el formato numérico, revise: " + e.getMessage());
            
            }
            // Si el usuario mete letras o deja el campo vacío, no hacemos cálculos para evitar errores
            
            
            // Resumen:
            // No se tocan consultas, ni tablas, se controla el origen del dato.
            // Es la forma más limpia de trabajar.
            // Automatización del cálculo Precio venta.
            
            // Se puede investigar el Evento --> KeyReleased: Funciona de la misma manera pero mientras el Usuario aún está tecleando.
        
    
    
    }//GEN-LAST:event_campoPrecioCompraFocusLost

    private void campoPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecioCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistrarArticulo dialog = new RegistrarArticulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrarArticulo;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextArea campoDescripcionArticulo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPrecioCompra;
    private javax.swing.JTextField campoPrecioVenta;
    private javax.swing.JTextField campoStock;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboDestacado;
    private javax.swing.JComboBox<String> comboOferta;
    private javax.swing.JComboBox<String> comboOrigen;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblImprimirAdmin;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTienda2;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JPanel panelSecundario1;
    // End of variables declaration//GEN-END:variables



    /**
     * Realiza el registro de un nuevo artículo en la base de datos.
     * Aplica validaciones sobre todos los campos del formulario antes de proceder.
     * Si todas las validaciones son correctas, rescata los valores, calcula el precio de venta automáticamente, crea un objeto y lo inserta en la base de datos.
     * Si el registro es correcto, muestra mensaje de confirmación y limpia el formulario.
     */
    public void registrarArticulo() {

        // Validaciones

    if (Utilidades.compruebaCampoVacio(campoCodigo)) {
        Utilidades.lanzaAlertaVacio(campoCodigo);

    } else if (Utilidades.compruebaCampoVacio(campoNombre)) {
        Utilidades.lanzaAlertaVacio(campoNombre);

    } else if (Utilidades.compruebaComboNoSeleccionado(comboCategoria)) {
        Utilidades.lanzaAlertaCombo(comboCategoria);

    } else if (Utilidades.compruebaComboNoSeleccionado(comboOrigen)) {
        Utilidades.lanzaAlertaCombo(comboOrigen);

    } else if (campoDescripcionArticulo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "El campo descripción en el registro de artículo no puede estar vacío.",
                    "Por favor, añada los datos requeridos.",
                    JOptionPane.WARNING_MESSAGE);

    } else if (Utilidades.compruebaCampoVacio(campoPrecioCompra)) {
        Utilidades.lanzaAlertaVacio(campoPrecioCompra);
        
    } else if (Utilidades.compruebaDouble(campoPrecioCompra)) {
        Utilidades.lanzaAlertaDoubleNoValido(campoPrecioCompra);

    } else if (!Utilidades.compruebaDouble(campoPrecioCompra)) { 
        Utilidades.lanzaAlertaDoubleNoValido(campoPrecioCompra);
        
    } else if (Utilidades.compruebaCampoVacio(campoPrecioVenta)) {
        Utilidades.lanzaAlertaVacio(campoPrecioVenta);

    } else if (!Utilidades.compruebaDouble(campoPrecioVenta)) { 
        Utilidades.lanzaAlertaDoubleNoValido(campoPrecioVenta);

    } else if (Utilidades.compruebaCampoVacio(campoStock)) {
        Utilidades.lanzaAlertaVacio(campoStock);

    } else if (!Utilidades.compruebaEntero(campoStock)) { 
        Utilidades.lanzaAlertaNumeroNoValido(campoStock);

    } else if (Utilidades.compruebaComboNoSeleccionado(comboDestacado)) {
        Utilidades.lanzaAlertaCombo(comboDestacado);

    } else if (Utilidades.compruebaComboNoSeleccionado(comboOferta)) {
        Utilidades.lanzaAlertaCombo(comboOferta);
    
    } else {

        // Rescatar valores
        String codProducto = campoCodigo.getText().trim();
        String nombre = campoNombre.getText().trim();
        String categoria = comboCategoria.getSelectedItem().toString();
        String descripcion = campoDescripcionArticulo.getText().trim();
        double precioCompra = Double.parseDouble(campoPrecioCompra.getText().trim());
        double precioVenta = Double.parseDouble(campoPrecioVenta.getText().trim());
        int stock = Integer.parseInt(campoStock.getText().trim());
        String origen = comboOrigen.getSelectedItem().toString();
        String destacado = comboDestacado.getSelectedItem().toString();
        String oferta = comboOferta.getSelectedItem().toString();
        Date fechaAlta = new Date();

        // Crear objeto producto
        Producto p = new Producto(codProducto, nombre, categoria, descripcion,
            precioCompra, precioVenta, stock, origen, destacado, oferta, fechaAlta); 

        // fechaAlta no aparece en Interfaz pero sí aquí
        // lo quitamos de Interfaz ya que no hace falta que aparezca allí 
        // pero sí que nos lo rescate para que lo mande a la BBDD
        
      
        if (ConsultasProducto.registrarProducto(p)) {
            
            JOptionPane.showMessageDialog(this, 
                    "Artículo registrado en inventario correctamente.");

        // Limpiar campos registrar artículo
        limpiarArticulo();
        
        } else {
                
                JOptionPane.showMessageDialog(this, 
                        "Error al registrar el artículo, no se pudo acceder al almacén de datos.");
        }
        
        }
    
    }


    /**
     * Limpia todos los campos del formulario de registro de artículo.
     * Automatiza y genera el siguiente Codigo de Producto al realizarse el reseteo y comenzar un nuevo registro.
     * Proporciona una buena experiencia al usuario.
     */
    public void limpiarArticulo() {
        //campoCodigo.setText(""); // Ya no hace falta pero lo dejo por si hubiera que modificarlo por si no gusta la idea.
        campoNombre.setText("");
        campoDescripcionArticulo.setText("");
        campoPrecioCompra.setText("");
        campoPrecioVenta.setText("");
        campoStock.setText("");
        comboCategoria.setSelectedIndex(0);
        comboOrigen.setSelectedIndex(0);
        comboDestacado.setSelectedIndex(0);
        comboOferta.setSelectedIndex(0);
        
        String sugerenciaCodigoProducto = ConsultasProducto.generarSiguienteCodigoProducto();
        campoCodigo.setText(sugerenciaCodigoProducto);
        campoCodigo.setEditable(false); // Bloqueado: Para que el usuario no lo cambie, no es requisito pero lo hemos decidido así para mejor funcionalidad
    }
    
    /**
     * Obtiene y carga dinámicamente todos los JComboBox de Categorías, Orígenes y valores ENUM (Oferta/Destacado) directamente de la BBDD.
     * Siempre restablece los componentes e inserta la opción "Seleccione" en el índice 0.
     */
    private void cargarCombosArticulos() {
        
        // Combo Categoría 
        comboCategoria.removeAllItems();
        comboCategoria.addItem("Seleccione");
        java.util.ArrayList<String> categorias = bbdd.ConsultasCategorias.obtenerCategorias();
        for (String categ : categorias) {
            comboCategoria.addItem(categ);
        }

        // Combo Origen 
        comboOrigen.removeAllItems();
        comboOrigen.addItem("Seleccione");
        java.util.ArrayList<String> origenes = bbdd.ConsultasOrigen.obtenerOrigenes();
        for (String orig : origenes) {
            comboOrigen.addItem(orig);
        }

        // Combo Destacado:  Saca el SI y NO de la tabla producto, columna destacado
        comboDestacado.removeAllItems();
        comboDestacado.addItem("Seleccione");
        
              // Le decimos: "Vete a la tabla 'producto' y saca los valores de 'destacado'"
        java.util.ArrayList<String> destacados = bbdd.Conexion.obtenerValoresEnum("producto", "destacado");
        for (String dest : destacados) {
            comboDestacado.addItem(dest);
        }
        
       // Combo Oferta:  Saca el SI y NO de la tabla producto, columna oferta
        comboOferta.removeAllItems();
        comboOferta.addItem("Seleccione");
        
        
        java.util.ArrayList<String> ofertas = bbdd.Conexion.obtenerValoresEnum("producto", "oferta");
        for (String of : ofertas) {
            comboOferta.addItem(of);
        }
    }
    
    
}
