/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.vistasAdmin;

import bbdd.ConsultasProducto;
import bbdd.ConsultasTiendas;
import bbdd.ConsultasUsuarios;
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;
import vistas.VentanaLogin;

/**
 *
 * @author jintae
 */
public class VentanaAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAdmin.class.getName());

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();

        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);

        // Rescatar fecha y hora en la interfaz
        LocalDateTime fechaHora = LocalDateTime.now();
        lblRescataFechayHora.setText("Admin activo — "
                + fechaHora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));

        // Rescata Administrador:
        lblImprimirAdmin.setText(VentanaLogin.user);

        // Cargar tabla 3 últimos artículos 
        ConsultasProducto.ultimos3Articulos((DefaultTableModel) tablaArticulosRegistrados.getModel());
        lblRescatarTiendas.setText(String.valueOf(ConsultasTiendas.rescataTienda()));
        lblRescatarProductoNacional.setText(String.valueOf(ConsultasProducto.rescatarProductosNacionales()));
        lblRescatarUsuariosTotales.setText(String.valueOf(ConsultasUsuarios.rescatarUsuariosTotales()));
        lblRescatarUsuariosActivos.setText(String.valueOf(ConsultasUsuarios.rescatarUsuariosActivos()));

        // Rescatar lbl de Tiendas abiertas, productos Nacionales, Usuarios Totales y Usuarios activos
        // Consultas en paquete de bbdd Consultas y rescatar aquí:
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblAcceso = new javax.swing.JLabel();
        panelAdminSidebar = new javax.swing.JPanel();
        botonRegistrarArticulo = new javax.swing.JButton();
        botonRegistrarUsuario = new javax.swing.JButton();
        botonVerOfertas = new javax.swing.JButton();
        botonVerUsuarios = new javax.swing.JButton();
        botonCategorias = new javax.swing.JButton();
        botonOrigenes = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonTienda = new javax.swing.JButton();
        botonVerMiCuenta = new javax.swing.JButton();
        botonVerDestacados = new javax.swing.JButton();
        botonVerArticulos = new javax.swing.JButton();
        panelRescatarLabels = new javax.swing.JPanel();
        lblRescatarTiendas = new javax.swing.JLabel();
        lblRescatarProductoNacional = new javax.swing.JLabel();
        lblRescatarUsuariosTotales = new javax.swing.JLabel();
        lblRescatarUsuariosActivos = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImprimirAdmin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulosRegistrados = new javax.swing.JTable();
        lblSubtitulo5 = new javax.swing.JLabel();
        menuBarAdmin = new javax.swing.JMenuBar();
        menuInventario = new javax.swing.JMenu();
        itemRegistrarArticulo = new javax.swing.JMenuItem();
        itemVerArticulos = new javax.swing.JMenuItem();
        itemDestacados = new javax.swing.JMenuItem();
        itemOfertas = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemRegistrarUsuario = new javax.swing.JMenuItem();
        itemVerUsuarios = new javax.swing.JMenuItem();
        menuTiendas = new javax.swing.JMenu();
        itemVerTiendas = new javax.swing.JMenuItem();
        itemCategorias = new javax.swing.JMenuItem();
        itemOrigenes = new javax.swing.JMenuItem();
        menuMiCuenta = new javax.swing.JMenu();
        itemVerMiCuenta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTANA PRINCIPAL ADMINISTRADOR");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(3, 32, 38));
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 3));
        panelLogo.setOpaque(false);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoEmpresaPequeño.jpg"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(191, 150, 99));
        lblNombre.setText("Ferretería JP Fusión");

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblLogo))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = -9;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 72, 0, 0);
        panelPrincipal.add(panelLogo, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo.setText("Panel de control");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 42, 0, 0);
        panelPrincipal.add(lblTitulo, gridBagConstraints);

        lblSubtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo.setText("Gestión de inventario y personal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 42, 0, 0);
        panelPrincipal.add(lblSubtitulo, gridBagConstraints);

        lblAcceso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblAcceso.setForeground(new java.awt.Color(112, 137, 140));
        lblAcceso.setText("ACCESO RÁPIDO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 91, 0, 0);
        panelPrincipal.add(lblAcceso, gridBagConstraints);

        panelAdminSidebar.setOpaque(false);

        botonRegistrarArticulo.setBackground(new java.awt.Color(9, 48, 64));
        botonRegistrarArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonRegistrarArticulo.setForeground(new java.awt.Color(191, 150, 99));
        botonRegistrarArticulo.setText("+ Registrar Artículo");
        botonRegistrarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarArticuloActionPerformed(evt);
            }
        });

        botonRegistrarUsuario.setBackground(new java.awt.Color(9, 48, 64));
        botonRegistrarUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonRegistrarUsuario.setForeground(new java.awt.Color(191, 150, 99));
        botonRegistrarUsuario.setText("+ Registrar Usuario");
        botonRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });

        botonVerOfertas.setBackground(new java.awt.Color(9, 48, 64));
        botonVerOfertas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerOfertas.setForeground(new java.awt.Color(191, 150, 99));
        botonVerOfertas.setText("Ver Ofertas");
        botonVerOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerOfertasActionPerformed(evt);
            }
        });

        botonVerUsuarios.setBackground(new java.awt.Color(9, 48, 64));
        botonVerUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerUsuarios.setForeground(new java.awt.Color(191, 150, 99));
        botonVerUsuarios.setText("Ver Usuarios");
        botonVerUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerUsuariosActionPerformed(evt);
            }
        });

        botonCategorias.setBackground(new java.awt.Color(9, 48, 64));
        botonCategorias.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonCategorias.setForeground(new java.awt.Color(191, 150, 99));
        botonCategorias.setText("Categorías");
        botonCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCategoriasActionPerformed(evt);
            }
        });

        botonOrigenes.setBackground(new java.awt.Color(9, 48, 64));
        botonOrigenes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonOrigenes.setForeground(new java.awt.Color(191, 150, 99));
        botonOrigenes.setText("Orígenes");
        botonOrigenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOrigenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrigenesActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(191, 150, 99));
        botonSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonSalir.setText("Salir del sistema");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonTienda.setBackground(new java.awt.Color(9, 48, 64));
        botonTienda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonTienda.setForeground(new java.awt.Color(191, 150, 99));
        botonTienda.setText("Tiendas");
        botonTienda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendaActionPerformed(evt);
            }
        });

        botonVerMiCuenta.setBackground(new java.awt.Color(9, 48, 64));
        botonVerMiCuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerMiCuenta.setForeground(new java.awt.Color(191, 150, 99));
        botonVerMiCuenta.setText("Mi cuenta");
        botonVerMiCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerMiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMiCuentaActionPerformed(evt);
            }
        });

        botonVerDestacados.setBackground(new java.awt.Color(9, 48, 64));
        botonVerDestacados.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerDestacados.setForeground(new java.awt.Color(191, 150, 99));
        botonVerDestacados.setText("Ver Destacados");
        botonVerDestacados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerDestacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerDestacadosActionPerformed(evt);
            }
        });

        botonVerArticulos.setBackground(new java.awt.Color(9, 48, 64));
        botonVerArticulos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerArticulos.setForeground(new java.awt.Color(191, 150, 99));
        botonVerArticulos.setText("Ver Artículos");
        botonVerArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerArticulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminSidebarLayout = new javax.swing.GroupLayout(panelAdminSidebar);
        panelAdminSidebar.setLayout(panelAdminSidebarLayout);
        panelAdminSidebarLayout.setHorizontalGroup(
            panelAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminSidebarLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(panelAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonOrigenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(botonVerOfertas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVerUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonTienda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVerMiCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVerDestacados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVerArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAdminSidebarLayout.setVerticalGroup(
            panelAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerDestacados, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonOrigenes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVerMiCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 47, 0, 0);
        panelPrincipal.add(panelAdminSidebar, gridBagConstraints);

        panelRescatarLabels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99)));
        panelRescatarLabels.setOpaque(false);

        lblRescatarTiendas.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarTiendas.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRescatarTiendas.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarTiendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarTiendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarTiendas.setOpaque(true);

        lblRescatarProductoNacional.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarProductoNacional.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRescatarProductoNacional.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarProductoNacional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarProductoNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarProductoNacional.setOpaque(true);

        lblRescatarUsuariosTotales.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarUsuariosTotales.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRescatarUsuariosTotales.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarUsuariosTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarUsuariosTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarUsuariosTotales.setOpaque(true);

        lblRescatarUsuariosActivos.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarUsuariosActivos.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRescatarUsuariosActivos.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarUsuariosActivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarUsuariosActivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarUsuariosActivos.setOpaque(true);

        lbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(191, 150, 99));
        lbl1.setText("Tiendas Abiertas");

        lbl4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(191, 150, 99));
        lbl4.setText("Usuarios Activos");

        lbl3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(191, 150, 99));
        lbl3.setText("Usuarios Totales");

        lbl2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(191, 150, 99));
        lbl2.setText("Productos Nacionales");

        javax.swing.GroupLayout panelRescatarLabelsLayout = new javax.swing.GroupLayout(panelRescatarLabels);
        panelRescatarLabels.setLayout(panelRescatarLabelsLayout);
        panelRescatarLabelsLayout.setHorizontalGroup(
            panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRescatarTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescatarProductoNacional, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRescatarUsuariosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRescatarUsuariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelRescatarLabelsLayout.setVerticalGroup(
            panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRescatarLabelsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl4)
                    .addComponent(lbl3)
                    .addComponent(lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRescatarTiendas, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(lblRescatarProductoNacional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescatarUsuariosTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescatarUsuariosActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = -47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 32, 0, 0);
        panelPrincipal.add(panelRescatarLabels, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(3, 32, 38));

        lblImprimirAdmin.setBackground(new java.awt.Color(9, 48, 64));
        lblImprimirAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblImprimirAdmin.setForeground(new java.awt.Color(191, 150, 99));
        lblImprimirAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(6, 6, 6)
                .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 337, 0, 0);
        panelPrincipal.add(jPanel1, gridBagConstraints);

        panelFinal.setBackground(new java.awt.Color(9, 48, 64));
        panelFinal.setForeground(new java.awt.Color(191, 150, 99));
        panelFinal.setOpaque(false);

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(3, 32, 38));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSistemaGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 115, 6, 0);
        panelPrincipal.add(panelFinal, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(3, 32, 38));

        tablaArticulosRegistrados.setBackground(new java.awt.Color(9, 48, 64));
        tablaArticulosRegistrados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 150, 99), 4, true));
        tablaArticulosRegistrados.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        tablaArticulosRegistrados.setForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "Stock", "Precio venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulosRegistrados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaArticulosRegistrados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaArticulosRegistrados.setEnabled(false);
        tablaArticulosRegistrados.setFillsViewportHeight(true);
        tablaArticulosRegistrados.setGridColor(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setRowHeight(40);
        tablaArticulosRegistrados.setSelectionBackground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setSelectionForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setShowGrid(false);
        tablaArticulosRegistrados.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tablaArticulosRegistrados);
        if (tablaArticulosRegistrados.getColumnModel().getColumnCount() > 0) {
            tablaArticulosRegistrados.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablaArticulosRegistrados.getColumnModel().getColumn(1).setPreferredWidth(150);
            tablaArticulosRegistrados.getColumnModel().getColumn(2).setPreferredWidth(130);
            tablaArticulosRegistrados.getColumnModel().getColumn(3).setPreferredWidth(10);
            tablaArticulosRegistrados.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        lblSubtitulo5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo5.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo5.setText("ARTICULOS AÑADIDOS RECIENTEMENTE A LA TIENDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtitulo5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblSubtitulo5)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        panelPrincipal.add(jPanel2, gridBagConstraints);

        menuBarAdmin.setBackground(new java.awt.Color(10, 49, 64));
        menuBarAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));
        menuBarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        menuBarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuInventario.setBackground(new java.awt.Color(10, 49, 64));
        menuInventario.setForeground(new java.awt.Color(10, 49, 64));
        menuInventario.setText("Inventario");
        menuInventario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemRegistrarArticulo.setBackground(new java.awt.Color(10, 49, 64));
        itemRegistrarArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemRegistrarArticulo.setForeground(new java.awt.Color(10, 49, 64));
        itemRegistrarArticulo.setText("Registrar Artículo");
        itemRegistrarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemRegistrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarArticuloActionPerformed(evt);
            }
        });
        menuInventario.add(itemRegistrarArticulo);

        itemVerArticulos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerArticulos.setForeground(new java.awt.Color(10, 49, 64));
        itemVerArticulos.setText("Ver Artículos");
        itemVerArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerArticulosActionPerformed(evt);
            }
        });
        menuInventario.add(itemVerArticulos);

        itemDestacados.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemDestacados.setForeground(new java.awt.Color(10, 49, 64));
        itemDestacados.setText("Destacados");
        itemDestacados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemDestacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDestacadosActionPerformed(evt);
            }
        });
        menuInventario.add(itemDestacados);

        itemOfertas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemOfertas.setForeground(new java.awt.Color(10, 49, 64));
        itemOfertas.setText("Ofertas");
        itemOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOfertasActionPerformed(evt);
            }
        });
        menuInventario.add(itemOfertas);

        menuBarAdmin.add(menuInventario);

        menuUsuarios.setForeground(new java.awt.Color(10, 49, 64));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemRegistrarUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemRegistrarUsuario.setForeground(new java.awt.Color(10, 49, 64));
        itemRegistrarUsuario.setText("Registrar Usuario");
        itemRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemRegistrarUsuario);

        itemVerUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerUsuarios.setForeground(new java.awt.Color(10, 49, 64));
        itemVerUsuarios.setText("Ver Usuarios");
        itemVerUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemVerUsuarios);

        menuBarAdmin.add(menuUsuarios);

        menuTiendas.setForeground(new java.awt.Color(10, 49, 64));
        menuTiendas.setText("Tiendas");
        menuTiendas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemVerTiendas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerTiendas.setForeground(new java.awt.Color(10, 49, 64));
        itemVerTiendas.setText("Ver Tiendas");
        itemVerTiendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerTiendasActionPerformed(evt);
            }
        });
        menuTiendas.add(itemVerTiendas);

        itemCategorias.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemCategorias.setForeground(new java.awt.Color(10, 49, 64));
        itemCategorias.setText("Categorías");
        itemCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriasActionPerformed(evt);
            }
        });
        menuTiendas.add(itemCategorias);

        itemOrigenes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemOrigenes.setForeground(new java.awt.Color(10, 49, 64));
        itemOrigenes.setText("Orígenes");
        itemOrigenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemOrigenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrigenesActionPerformed(evt);
            }
        });
        menuTiendas.add(itemOrigenes);

        menuBarAdmin.add(menuTiendas);

        menuMiCuenta.setForeground(new java.awt.Color(10, 49, 64));
        menuMiCuenta.setText("Mi cuenta");
        menuMiCuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemVerMiCuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerMiCuenta.setText("Ver mi cuenta");
        itemVerMiCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerMiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerMiCuentaActionPerformed(evt);
            }
        });
        menuMiCuenta.add(itemVerMiCuenta);

        menuBarAdmin.add(menuMiCuenta);

        jMenu1.setText("Ayuda");
        jMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jMenuItem1.setText("Acerca de");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBarAdmin.add(jMenu1);

        setJMenuBar(menuBarAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        utilidades.Utilidades.salirAplicacion(this);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed
        RegistrarUsuario regusu = new RegistrarUsuario(this, true);
        regusu.setVisible(true);
    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    private void botonVerOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerOfertasActionPerformed
        VerListadoOfertas vlistof = new VerListadoOfertas(this, true);
        vlistof.setVisible(true);
    }//GEN-LAST:event_botonVerOfertasActionPerformed

    private void botonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCategoriasActionPerformed
        VerListadoCategorias vlistcat = new VerListadoCategorias(this, true);
        vlistcat.setVisible(true);
    }//GEN-LAST:event_botonCategoriasActionPerformed

    private void botonVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerUsuariosActionPerformed
        VerListadoUsuarios vlistusu = new VerListadoUsuarios(this, true);
        vlistusu.setVisible(true);
    }//GEN-LAST:event_botonVerUsuariosActionPerformed

    private void botonOrigenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrigenesActionPerformed
        VerListadoOrigen vlistor = new VerListadoOrigen(this, true);
        vlistor.setVisible(true);
    }//GEN-LAST:event_botonOrigenesActionPerformed

    private void itemRegistrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarArticuloActionPerformed
        RegistrarArticulo regart = new RegistrarArticulo(this, true);
        regart.setVisible(true);
    }//GEN-LAST:event_itemRegistrarArticuloActionPerformed

    private void itemVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerArticulosActionPerformed
        VerListadoArticulos vlistart = new VerListadoArticulos(this, true);
        vlistart.setVisible(true);
    }//GEN-LAST:event_itemVerArticulosActionPerformed

    private void itemDestacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDestacadosActionPerformed
        VerListadoDestacados vlistdes = new VerListadoDestacados(this, true);
        vlistdes.setVisible(true);
    }//GEN-LAST:event_itemDestacadosActionPerformed

    private void itemOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOfertasActionPerformed
        VerListadoOfertas vlistof = new VerListadoOfertas(this, true);
        vlistof.setVisible(true);
    }//GEN-LAST:event_itemOfertasActionPerformed

    private void itemRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarUsuarioActionPerformed
        RegistrarUsuario regusu = new RegistrarUsuario(this, true);
        regusu.setVisible(true);
    }//GEN-LAST:event_itemRegistrarUsuarioActionPerformed

    private void itemVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerUsuariosActionPerformed
        VerListadoUsuarios vlistusu = new VerListadoUsuarios(this, true);
        vlistusu.setVisible(true);
    }//GEN-LAST:event_itemVerUsuariosActionPerformed

    private void itemVerTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerTiendasActionPerformed
        VerListadoTiendas vlisttien = new VerListadoTiendas(this, true);
        vlisttien.setVisible(true);
    }//GEN-LAST:event_itemVerTiendasActionPerformed

    private void itemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriasActionPerformed
        VerListadoCategorias vlistcat = new VerListadoCategorias(this, true);
        vlistcat.setVisible(true);
    }//GEN-LAST:event_itemCategoriasActionPerformed

    private void itemOrigenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrigenesActionPerformed
        VerListadoOrigen vlistor = new VerListadoOrigen(this, true);
        vlistor.setVisible(true);
    }//GEN-LAST:event_itemOrigenesActionPerformed

    private void botonRegistrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarArticuloActionPerformed
        RegistrarArticulo regart = new RegistrarArticulo(this, true);
        regart.setVisible(true);
    }//GEN-LAST:event_botonRegistrarArticuloActionPerformed

    private void itemVerMiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerMiCuentaActionPerformed
        VerDatosCuenta vdatcuent = new VerDatosCuenta(this, true);
        vdatcuent.setVisible(true);
    }//GEN-LAST:event_itemVerMiCuentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        utilidades.Utilidades.mostrarAcercaDe(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botonTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendaActionPerformed
        VerListadoTiendas vlt = new VerListadoTiendas(this, true);
        vlt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_botonTiendaActionPerformed

    private void botonVerMiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMiCuentaActionPerformed
        VerDatosCuenta vdatcuent = new VerDatosCuenta(this, true);
        vdatcuent.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerMiCuentaActionPerformed

    private void botonVerDestacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDestacadosActionPerformed
        VerListadoDestacados vlistdes = new VerListadoDestacados(this, true);
        vlistdes.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerDestacadosActionPerformed

    private void botonVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerArticulosActionPerformed
        VerListadoArticulos vlistart = new VerListadoArticulos(this, true);
        vlistart.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerArticulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCategorias;
    private javax.swing.JButton botonOrigenes;
    private javax.swing.JButton botonRegistrarArticulo;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTienda;
    private javax.swing.JButton botonVerArticulos;
    private javax.swing.JButton botonVerDestacados;
    private javax.swing.JButton botonVerMiCuenta;
    private javax.swing.JButton botonVerOfertas;
    private javax.swing.JButton botonVerUsuarios;
    private javax.swing.JMenuItem itemCategorias;
    private javax.swing.JMenuItem itemDestacados;
    private javax.swing.JMenuItem itemOfertas;
    private javax.swing.JMenuItem itemOrigenes;
    private javax.swing.JMenuItem itemRegistrarArticulo;
    private javax.swing.JMenuItem itemRegistrarUsuario;
    private javax.swing.JMenuItem itemVerArticulos;
    private javax.swing.JMenuItem itemVerMiCuenta;
    private javax.swing.JMenuItem itemVerTiendas;
    private javax.swing.JMenuItem itemVerUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblAcceso;
    private javax.swing.JLabel lblImprimirAdmin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblRescatarProductoNacional;
    private javax.swing.JLabel lblRescatarTiendas;
    private javax.swing.JLabel lblRescatarUsuariosActivos;
    private javax.swing.JLabel lblRescatarUsuariosTotales;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtitulo5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar menuBarAdmin;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu menuMiCuenta;
    private javax.swing.JMenu menuTiendas;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel panelAdminSidebar;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRescatarLabels;
    private javax.swing.JTable tablaArticulosRegistrados;
    // End of variables declaration//GEN-END:variables

}
