/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.vistasAdmin;

import java.time.LocalDateTime;
import vistas.VentanaLogin;

/**
 *
 * @author jintae
 */
public class VentanaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAdmin.class.getName());

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
        
        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);
        
        // Rescatar fecha y hora en la interfaz
        LocalDateTime fechaHora = LocalDateTime.now();
        lblRescataFechayHora.setText("Admin activo — " 
                + fechaHora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
        
        // Rescata Administrador:
        lblImprimirAdmin.setText(VentanaLogin.user);
        
        // Rescatar lbl de Tiendas abiertas, productos Nacionales, Usuarios Totales y Usuarios activos
        // Consultas en paquete de bbdd Consultas y rescatar aquí:
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblAcceso = new javax.swing.JLabel();
        panelAdminSidebar = new javax.swing.JPanel();
        botonRegistrarArticulo = new javax.swing.JButton();
        botonRegistrarUsuario = new javax.swing.JButton();
        botonVerArticulos = new javax.swing.JButton();
        botonVerUsuarios = new javax.swing.JButton();
        botonCategorias = new javax.swing.JButton();
        botonOrigenes = new javax.swing.JButton();
        botonTiendas = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelRescatarLabels = new javax.swing.JPanel();
        lblRescatarTiendas = new javax.swing.JLabel();
        lblRescatarProductoNacional = new javax.swing.JLabel();
        lblRescatarUsuariosTotales = new javax.swing.JLabel();
        lblRescatarUsuariosActivos = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulosRegistrados = new javax.swing.JTable();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        lblNovedadesInventario1 = new javax.swing.JLabel();
        lblImprimirAdmin = new javax.swing.JLabel();
        menuBarAdmin = new javax.swing.JMenuBar();
        menuInventario = new javax.swing.JMenu();
        itemRegistrarArticulo = new javax.swing.JMenuItem();
        itemVerArticulos = new javax.swing.JMenuItem();
        itemDestacados = new javax.swing.JMenuItem();
        itemOfertas = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemRegistrarUsuario = new javax.swing.JMenuItem();
        itemVerUsuarios = new javax.swing.JMenuItem();
        menuTiendas = new javax.swing.JMenu();
        itemVerTiendas = new javax.swing.JMenuItem();
        itemCategorias = new javax.swing.JMenuItem();
        itemOrigenes = new javax.swing.JMenuItem();
        menuMiCuenta = new javax.swing.JMenu();
        itemVerMiCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTANA PRINCIPAL ADMINISTRADOR");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(3, 32, 38));

        panelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 3));
        panelLogo.setOpaque(false);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoEmpresaPequeño.jpg"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(191, 150, 99));
        lblNombre.setText("Ferretería JP Fusión");

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(50, 50, 50))
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAdmin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(191, 150, 99));
        lblAdmin.setText("Administrador:");

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo.setText("Panel de control");

        lblSubtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo.setText("Gestión de inventario y personal");

        lblAcceso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblAcceso.setForeground(new java.awt.Color(112, 137, 140));
        lblAcceso.setText("ACCESO RÁPIDO");

        panelAdminSidebar.setOpaque(false);

        botonRegistrarArticulo.setBackground(new java.awt.Color(9, 48, 64));
        botonRegistrarArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonRegistrarArticulo.setForeground(new java.awt.Color(191, 150, 99));
        botonRegistrarArticulo.setText("+ Registrar Artículo");
        botonRegistrarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarArticuloActionPerformed(evt);
            }
        });

        botonRegistrarUsuario.setBackground(new java.awt.Color(9, 48, 64));
        botonRegistrarUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonRegistrarUsuario.setForeground(new java.awt.Color(191, 150, 99));
        botonRegistrarUsuario.setText("+ Registrar Usuario");
        botonRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });

        botonVerArticulos.setBackground(new java.awt.Color(9, 48, 64));
        botonVerArticulos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerArticulos.setForeground(new java.awt.Color(191, 150, 99));
        botonVerArticulos.setText("Ver Artículos");
        botonVerArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerArticulosActionPerformed(evt);
            }
        });

        botonVerUsuarios.setBackground(new java.awt.Color(9, 48, 64));
        botonVerUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerUsuarios.setForeground(new java.awt.Color(191, 150, 99));
        botonVerUsuarios.setText("Ver Usuarios");
        botonVerUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerUsuariosActionPerformed(evt);
            }
        });

        botonCategorias.setBackground(new java.awt.Color(9, 48, 64));
        botonCategorias.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonCategorias.setForeground(new java.awt.Color(191, 150, 99));
        botonCategorias.setText("Categorías");
        botonCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCategoriasActionPerformed(evt);
            }
        });

        botonOrigenes.setBackground(new java.awt.Color(9, 48, 64));
        botonOrigenes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonOrigenes.setForeground(new java.awt.Color(191, 150, 99));
        botonOrigenes.setText("Orígenes");
        botonOrigenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOrigenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrigenesActionPerformed(evt);
            }
        });

        botonTiendas.setBackground(new java.awt.Color(9, 48, 64));
        botonTiendas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonTiendas.setForeground(new java.awt.Color(191, 150, 99));
        botonTiendas.setText("Tiendas");
        botonTiendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiendasActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(191, 150, 99));
        botonSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonSalir.setText("Salir del sistema");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminSidebarLayout = new javax.swing.GroupLayout(panelAdminSidebar);
        panelAdminSidebar.setLayout(panelAdminSidebarLayout);
        panelAdminSidebarLayout.setHorizontalGroup(
            panelAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminSidebarLayout.createSequentialGroup()
                .addGroup(panelAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAdminSidebarLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(panelAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonOrigenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(botonVerArticulos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVerUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAdminSidebarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botonTiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
            .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAdminSidebarLayout.setVerticalGroup(
            panelAdminSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonRegistrarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(botonVerArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonOrigenes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelRescatarLabels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99)));
        panelRescatarLabels.setOpaque(false);

        lblRescatarTiendas.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarTiendas.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarTiendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarTiendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarTiendas.setOpaque(true);

        lblRescatarProductoNacional.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarProductoNacional.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarProductoNacional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarProductoNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarProductoNacional.setOpaque(true);

        lblRescatarUsuariosTotales.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarUsuariosTotales.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarUsuariosTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarUsuariosTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarUsuariosTotales.setOpaque(true);

        lblRescatarUsuariosActivos.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarUsuariosActivos.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarUsuariosActivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarUsuariosActivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarUsuariosActivos.setOpaque(true);

        lbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(191, 150, 99));
        lbl1.setText("Tiendas Abiertas");

        lbl4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(191, 150, 99));
        lbl4.setText("Usuarios Activos");

        lbl3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(191, 150, 99));
        lbl3.setText("Usuarios Totales");

        lbl2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(191, 150, 99));
        lbl2.setText("Productos Nacionales");

        javax.swing.GroupLayout panelRescatarLabelsLayout = new javax.swing.GroupLayout(panelRescatarLabels);
        panelRescatarLabels.setLayout(panelRescatarLabelsLayout);
        panelRescatarLabelsLayout.setHorizontalGroup(
            panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRescatarLabelsLayout.createSequentialGroup()
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblRescatarTiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addGap(30, 30, 30)
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                        .addComponent(lblRescatarProductoNacional, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRescatarUsuariosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(lblRescatarUsuariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRescatarLabelsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        panelRescatarLabelsLayout.setVerticalGroup(
            panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRescatarLabelsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl4)
                    .addComponent(lbl3)
                    .addComponent(lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRescatarTiendas, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(lblRescatarProductoNacional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescatarUsuariosTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescatarUsuariosActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        tablaArticulosRegistrados.setBackground(new java.awt.Color(9, 48, 64));
        tablaArticulosRegistrados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));
        tablaArticulosRegistrados.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tablaArticulosRegistrados.setForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "Stock", "Precio venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulosRegistrados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaArticulosRegistrados.setEnabled(false);
        tablaArticulosRegistrados.setGridColor(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setSelectionBackground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setSelectionForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setShowGrid(false);
        jScrollPane1.setViewportView(tablaArticulosRegistrados);

        panelFinal.setBackground(new java.awt.Color(9, 48, 64));
        panelFinal.setForeground(new java.awt.Color(191, 150, 99));

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(3, 32, 38));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSistemaGestion)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lblNovedadesInventario1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNovedadesInventario1.setForeground(new java.awt.Color(191, 150, 99));
        lblNovedadesInventario1.setText("Novedades de inventario");

        lblImprimirAdmin.setBackground(new java.awt.Color(9, 48, 64));
        lblImprimirAdmin.setForeground(new java.awt.Color(191, 150, 99));
        lblImprimirAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImprimirAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblImprimirAdmin.setOpaque(true);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAdminSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitulo)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNovedadesInventario1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(panelRescatarLabels, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAcceso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAdminSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAdmin)
                                    .addComponent(lblTitulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubtitulo))
                            .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(panelRescatarLabels, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNovedadesInventario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBarAdmin.setBackground(new java.awt.Color(10, 49, 64));
        menuBarAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));
        menuBarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuInventario.setBackground(new java.awt.Color(10, 49, 64));
        menuInventario.setForeground(new java.awt.Color(10, 49, 64));
        menuInventario.setText("Inventario");
        menuInventario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemRegistrarArticulo.setBackground(new java.awt.Color(10, 49, 64));
        itemRegistrarArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemRegistrarArticulo.setForeground(new java.awt.Color(10, 49, 64));
        itemRegistrarArticulo.setText("Registrar Artículo");
        itemRegistrarArticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemRegistrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarArticuloActionPerformed(evt);
            }
        });
        menuInventario.add(itemRegistrarArticulo);

        itemVerArticulos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerArticulos.setForeground(new java.awt.Color(10, 49, 64));
        itemVerArticulos.setText("Ver Artículos");
        itemVerArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerArticulosActionPerformed(evt);
            }
        });
        menuInventario.add(itemVerArticulos);

        itemDestacados.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemDestacados.setForeground(new java.awt.Color(10, 49, 64));
        itemDestacados.setText("Destacados");
        itemDestacados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemDestacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDestacadosActionPerformed(evt);
            }
        });
        menuInventario.add(itemDestacados);

        itemOfertas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemOfertas.setForeground(new java.awt.Color(10, 49, 64));
        itemOfertas.setText("Ofertas");
        itemOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOfertasActionPerformed(evt);
            }
        });
        menuInventario.add(itemOfertas);

        menuBarAdmin.add(menuInventario);

        menuUsuarios.setForeground(new java.awt.Color(10, 49, 64));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemRegistrarUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemRegistrarUsuario.setForeground(new java.awt.Color(10, 49, 64));
        itemRegistrarUsuario.setText("Registrar Usuario");
        itemRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemRegistrarUsuario);

        itemVerUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerUsuarios.setForeground(new java.awt.Color(10, 49, 64));
        itemVerUsuarios.setText("Ver Usuarios");
        itemVerUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemVerUsuarios);

        menuBarAdmin.add(menuUsuarios);

        menuTiendas.setForeground(new java.awt.Color(10, 49, 64));
        menuTiendas.setText("Tiendas");
        menuTiendas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemVerTiendas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerTiendas.setForeground(new java.awt.Color(10, 49, 64));
        itemVerTiendas.setText("Ver Tiendas");
        itemVerTiendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerTiendasActionPerformed(evt);
            }
        });
        menuTiendas.add(itemVerTiendas);

        itemCategorias.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemCategorias.setForeground(new java.awt.Color(10, 49, 64));
        itemCategorias.setText("Categorías");
        itemCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriasActionPerformed(evt);
            }
        });
        menuTiendas.add(itemCategorias);

        itemOrigenes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemOrigenes.setForeground(new java.awt.Color(10, 49, 64));
        itemOrigenes.setText("Orígenes");
        itemOrigenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemOrigenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrigenesActionPerformed(evt);
            }
        });
        menuTiendas.add(itemOrigenes);

        menuBarAdmin.add(menuTiendas);

        menuMiCuenta.setForeground(new java.awt.Color(10, 49, 64));
        menuMiCuenta.setText("Mi cuenta");
        menuMiCuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemVerMiCuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerMiCuenta.setText("Ver mi cuenta");
        itemVerMiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerMiCuentaActionPerformed(evt);
            }
        });
        menuMiCuenta.add(itemVerMiCuenta);

        menuBarAdmin.add(menuMiCuenta);

        setJMenuBar(menuBarAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        utilidades.Utilidades.salirAplicacion(this);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed
        RegistrarUsuario regusu = new RegistrarUsuario(this, true);
        regusu.setVisible(true);
    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    private void botonVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerArticulosActionPerformed
        VerListadoArticulos vlistart = new VerListadoArticulos(this, true);
        vlistart.setVisible(true);
    }//GEN-LAST:event_botonVerArticulosActionPerformed

    private void botonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCategoriasActionPerformed
        VerListadoCategorias vlistcat = new VerListadoCategorias(this, true);
        vlistcat.setVisible(true);
    }//GEN-LAST:event_botonCategoriasActionPerformed

    private void botonVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerUsuariosActionPerformed
        VerListadoUsuarios vlistusu = new VerListadoUsuarios(this, true);
        vlistusu.setVisible(true);
    }//GEN-LAST:event_botonVerUsuariosActionPerformed

    private void botonOrigenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrigenesActionPerformed
        VerListadoOrigen vlistor = new VerListadoOrigen(this, true);
        vlistor.setVisible(true);
    }//GEN-LAST:event_botonOrigenesActionPerformed

    private void botonTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiendasActionPerformed
        VerListadoTiendas vlisttien = new VerListadoTiendas(this, true);
        vlisttien.setVisible(true);
    }//GEN-LAST:event_botonTiendasActionPerformed

    private void itemRegistrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarArticuloActionPerformed
        RegistrarArticulo regart = new RegistrarArticulo(this, true);
        regart.setVisible(true);
    }//GEN-LAST:event_itemRegistrarArticuloActionPerformed

    private void itemVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerArticulosActionPerformed
        VerListadoArticulos vlistart = new VerListadoArticulos(this, true);
        vlistart.setVisible(true);
    }//GEN-LAST:event_itemVerArticulosActionPerformed

    private void itemDestacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDestacadosActionPerformed
        VerListadoDestacados vlistdes = new VerListadoDestacados(this, true);
        vlistdes.setVisible(true);
    }//GEN-LAST:event_itemDestacadosActionPerformed

    private void itemOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOfertasActionPerformed
        VerListadoOfertas vlistof = new VerListadoOfertas(this, true);
        vlistof.setVisible(true);
    }//GEN-LAST:event_itemOfertasActionPerformed

    private void itemRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarUsuarioActionPerformed
        RegistrarUsuario regusu = new RegistrarUsuario(this, true);
        regusu.setVisible(true);
    }//GEN-LAST:event_itemRegistrarUsuarioActionPerformed

    private void itemVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerUsuariosActionPerformed
        VerListadoUsuarios vlistusu = new VerListadoUsuarios(this, true);
        vlistusu.setVisible(true);
    }//GEN-LAST:event_itemVerUsuariosActionPerformed

    private void itemVerTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerTiendasActionPerformed
        VerListadoTiendas vlisttien = new VerListadoTiendas(this, true);
        vlisttien.setVisible(true);
    }//GEN-LAST:event_itemVerTiendasActionPerformed

    private void itemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriasActionPerformed
        VerListadoCategorias vlistcat = new VerListadoCategorias(this, true);
        vlistcat.setVisible(true);
    }//GEN-LAST:event_itemCategoriasActionPerformed

    private void itemOrigenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrigenesActionPerformed
        VerListadoOrigen vlistor = new VerListadoOrigen(this, true);
        vlistor.setVisible(true);
    }//GEN-LAST:event_itemOrigenesActionPerformed

    private void botonRegistrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarArticuloActionPerformed
        RegistrarArticulo regart = new RegistrarArticulo(this, true);
        regart.setVisible(true);
    }//GEN-LAST:event_botonRegistrarArticuloActionPerformed

    private void itemVerMiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerMiCuentaActionPerformed
        VerDatosCuenta vdatcuent = new VerDatosCuenta(this, true);
        vdatcuent.setVisible(true);
    }//GEN-LAST:event_itemVerMiCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCategorias;
    private javax.swing.JButton botonOrigenes;
    private javax.swing.JButton botonRegistrarArticulo;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTiendas;
    private javax.swing.JButton botonVerArticulos;
    private javax.swing.JButton botonVerUsuarios;
    private javax.swing.JMenuItem itemCategorias;
    private javax.swing.JMenuItem itemDestacados;
    private javax.swing.JMenuItem itemOfertas;
    private javax.swing.JMenuItem itemOrigenes;
    private javax.swing.JMenuItem itemRegistrarArticulo;
    private javax.swing.JMenuItem itemRegistrarUsuario;
    private javax.swing.JMenuItem itemVerArticulos;
    private javax.swing.JMenuItem itemVerMiCuenta;
    private javax.swing.JMenuItem itemVerTiendas;
    private javax.swing.JMenuItem itemVerUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblAcceso;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblImprimirAdmin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNovedadesInventario1;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblRescatarProductoNacional;
    private javax.swing.JLabel lblRescatarTiendas;
    private javax.swing.JLabel lblRescatarUsuariosActivos;
    private javax.swing.JLabel lblRescatarUsuariosTotales;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar menuBarAdmin;
    private javax.swing.JMenu menuInventario;
    private javax.swing.JMenu menuMiCuenta;
    private javax.swing.JMenu menuTiendas;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JPanel panelAdminSidebar;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRescatarLabels;
    private javax.swing.JTable tablaArticulosRegistrados;
    // End of variables declaration//GEN-END:variables
}
