/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.vistasAdmin;

/**
 *
 * @author jintae
 */
public class VerDatosCuenta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerDatosCuenta.class.getName());

    /**
     * Creates new form VerDatosCuenta
     */
    public VerDatosCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal8 = new javax.swing.JPanel();
        lblTitulo8 = new javax.swing.JLabel();
        lblSubtitulo8 = new javax.swing.JLabel();
        jToolBar9 = new javax.swing.JToolBar();
        panelSecundario8 = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        lblDenominacion1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        lblDenominacion2 = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JTextField();
        lblDenominacion3 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        lblDenominacion4 = new javax.swing.JLabel();
        lblDenominacion5 = new javax.swing.JLabel();
        lblDenominacion6 = new javax.swing.JLabel();
        campoPassActual = new javax.swing.JTextField();
        campoNewPass = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textImprimirUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA DATOS CUENTA");
        setResizable(false);

        panelPrincipal8.setBackground(new java.awt.Color(3, 32, 38));

        lblTitulo8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo8.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo8.setText("Mi cuenta");

        lblSubtitulo8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo8.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo8.setText("Consulta y actualización de datos personales");

        jToolBar9.setBackground(new java.awt.Color(191, 150, 99));
        jToolBar9.setRollover(true);
        jToolBar9.setMaximumSize(new java.awt.Dimension(2, 2));
        jToolBar9.setMinimumSize(new java.awt.Dimension(2, 2));

        panelSecundario8.setBackground(new java.awt.Color(9, 48, 64));

        botonVolver.setBackground(new java.awt.Color(3, 32, 38));
        botonVolver.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(191, 150, 99));
        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonActualizar.setBackground(new java.awt.Color(191, 150, 99));
        botonActualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonActualizar.setText("ACTUALIZAR");
        botonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDenominacion1.setBackground(new java.awt.Color(191, 150, 99));
        lblDenominacion1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDenominacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominacion1.setText("Nombre");
        lblDenominacion1.setOpaque(true);

        campoNombre.setBackground(new java.awt.Color(3, 32, 38));
        campoNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(112, 137, 140));
        campoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoNombre.setName("Denominación"); // NOI18N

        lblDenominacion2.setBackground(new java.awt.Color(191, 150, 99));
        lblDenominacion2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDenominacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominacion2.setText("Apellidos");
        lblDenominacion2.setOpaque(true);

        campoApellidos.setBackground(new java.awt.Color(3, 32, 38));
        campoApellidos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoApellidos.setForeground(new java.awt.Color(112, 137, 140));
        campoApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoApellidos.setName("Denominación"); // NOI18N

        lblDenominacion3.setBackground(new java.awt.Color(191, 150, 99));
        lblDenominacion3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDenominacion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominacion3.setText("Usuario");
        lblDenominacion3.setEnabled(false);
        lblDenominacion3.setOpaque(true);

        campoUsuario.setBackground(new java.awt.Color(3, 32, 38));
        campoUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(112, 137, 140));
        campoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoUsuario.setEnabled(false);
        campoUsuario.setName("Denominación"); // NOI18N

        lblDenominacion4.setBackground(new java.awt.Color(191, 150, 99));
        lblDenominacion4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDenominacion4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominacion4.setText("Contraseña actual");
        lblDenominacion4.setOpaque(true);

        lblDenominacion5.setBackground(new java.awt.Color(191, 150, 99));
        lblDenominacion5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDenominacion5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominacion5.setText("Nueva contraseña");
        lblDenominacion5.setOpaque(true);

        lblDenominacion6.setBackground(new java.awt.Color(191, 150, 99));
        lblDenominacion6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblDenominacion6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenominacion6.setText("Tipo");
        lblDenominacion6.setEnabled(false);
        lblDenominacion6.setOpaque(true);

        campoPassActual.setBackground(new java.awt.Color(3, 32, 38));
        campoPassActual.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPassActual.setForeground(new java.awt.Color(112, 137, 140));
        campoPassActual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPassActual.setName("Denominación"); // NOI18N

        campoNewPass.setBackground(new java.awt.Color(3, 32, 38));
        campoNewPass.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoNewPass.setForeground(new java.awt.Color(112, 137, 140));
        campoNewPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoNewPass.setName("Denominación"); // NOI18N

        campoTipo.setBackground(new java.awt.Color(3, 32, 38));
        campoTipo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoTipo.setForeground(new java.awt.Color(112, 137, 140));
        campoTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoTipo.setEnabled(false);
        campoTipo.setName("Denominación"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(9, 48, 64));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(191, 150, 99));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JP");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));

        javax.swing.GroupLayout panelSecundario8Layout = new javax.swing.GroupLayout(panelSecundario8);
        panelSecundario8.setLayout(panelSecundario8Layout);
        panelSecundario8Layout.setHorizontalGroup(
            panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundario8Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSecundario8Layout.createSequentialGroup()
                        .addGap(0, 218, Short.MAX_VALUE)
                        .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(botonVolver))
                    .addGroup(panelSecundario8Layout.createSequentialGroup()
                        .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDenominacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDenominacion5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDenominacion6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDenominacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDenominacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDenominacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoNewPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(campoPassActual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTipo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundario8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        panelSecundario8Layout.setVerticalGroup(
            panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundario8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDenominacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDenominacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDenominacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDenominacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPassActual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDenominacion5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDenominacion6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSecundario8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVolver, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(3, 32, 38));

        textImprimirUsuario.setBackground(new java.awt.Color(9, 48, 64));
        textImprimirUsuario.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        textImprimirUsuario.setForeground(new java.awt.Color(191, 150, 99));
        textImprimirUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(6, 6, 6)
                .addComponent(textImprimirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(textImprimirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        panelFinal.setBackground(new java.awt.Color(9, 48, 64));
        panelFinal.setForeground(new java.awt.Color(191, 150, 99));
        panelFinal.setOpaque(false);

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(3, 32, 38));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSistemaGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelPrincipal8Layout = new javax.swing.GroupLayout(panelPrincipal8);
        panelPrincipal8.setLayout(panelPrincipal8Layout);
        panelPrincipal8Layout.setHorizontalGroup(
            panelPrincipal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipal8Layout.createSequentialGroup()
                .addGroup(panelPrincipal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipal8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelPrincipal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitulo8)
                            .addGroup(panelPrincipal8Layout.createSequentialGroup()
                                .addComponent(lblTitulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipal8Layout.createSequentialGroup()
                        .addGap(0, 340, Short.MAX_VALUE)
                        .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipal8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelSecundario8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelPrincipal8Layout.setVerticalGroup(
            panelPrincipal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipal8Layout.createSequentialGroup()
                .addGroup(panelPrincipal8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipal8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTitulo8))
                    .addGroup(panelPrincipal8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelSecundario8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));

        menuArchivo.setText("Archivo");
        menuArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuArchivo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemCerrar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemCerrar.setText("Cerrar");
        itemCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCerrar);

        jMenuBar1.add(menuArchivo);

        menuAyuda.setText("Ayuda");
        menuAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAyuda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemAcercaDe.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        utilidades.Utilidades.mostrarAcercaDe(this);
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VerDatosCuenta dialog = new VerDatosCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoNewPass;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPassActual;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar9;
    private javax.swing.JLabel lblDenominacion1;
    private javax.swing.JLabel lblDenominacion2;
    private javax.swing.JLabel lblDenominacion3;
    private javax.swing.JLabel lblDenominacion4;
    private javax.swing.JLabel lblDenominacion5;
    private javax.swing.JLabel lblDenominacion6;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo8;
    private javax.swing.JLabel lblTitulo8;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelPrincipal8;
    private javax.swing.JPanel panelSecundario8;
    private javax.swing.JLabel textImprimirUsuario;
    // End of variables declaration//GEN-END:variables
}
