/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.vistasAdmin;

import bbdd.ConsultasUsuarios;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidades.Utilidades;
import vistas.VentanaLogin;

/**
 * Ventana de listado de usuarios del sistema.
 * Permite visualizar todos los empleados y modificar exclusivamente su Tienda asignada, su Tipo (Rol) y su Estado (Activo / Bloqueado).
 * @author Jose y Patricia
 */
public class VerListadoUsuarios extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerListadoUsuarios.class.getName());

    /**
     * Creates new form VerListadoUsuarios
     */
    public VerListadoUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Cargar tabla al abrir
        ConsultasUsuarios.listadoUsuarios((DefaultTableModel) tablaListadoUsuarios.getModel());
        
         //Este código pone el color de la tabla en el color oscuro y mantiene la letra en dorado para que se pueda ver.
        tablaListadoUsuarios.setSelectionBackground(new java.awt.Color(3, 32, 38));
        tablaListadoUsuarios.setSelectionForeground(new java.awt.Color(191, 150, 99));
        
        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);
        
        // Rescatar fecha y hora en la interfaz
        LocalDateTime fechaHora = LocalDateTime.now();
        lblRescataFechayHora.setText("Admin activo — "
                + fechaHora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));

        // Rescata Administrador:
        lblImprimirAdmin.setText(VentanaLogin.user);
        
        // Cargar combo y campos:
        cargarCombos();
        desactivarEdicion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblImprimirAdmin = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonNuevo = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblUsuario2 = new javax.swing.JLabel();
        lblUsuario3 = new javax.swing.JLabel();
        lblUsuario4 = new javax.swing.JLabel();
        lblUsuario5 = new javax.swing.JLabel();
        lblUsuario6 = new javax.swing.JLabel();
        lblUsuario7 = new javax.swing.JLabel();
        lblUsuario8 = new javax.swing.JLabel();
        lblUsuario9 = new javax.swing.JLabel();
        campoIdEmpleado = new javax.swing.JTextField();
        campoNombreCompleto = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        comboTienda = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        comboEstado = new javax.swing.JComboBox<>();
        campoFechaAlta = new javax.swing.JTextField();
        campoPass = new javax.swing.JPasswordField();
        botonEditarDatos = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA LISTADO USUARIOS");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(3, 32, 38));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo.setText("Listado de usuarios ");

        lblSubtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo.setText("Listado y actualización de usuarios de todas las tiendas");

        tablaListadoUsuarios.setBackground(new java.awt.Color(9, 48, 64));
        tablaListadoUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));
        tablaListadoUsuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tablaListadoUsuarios.setForeground(new java.awt.Color(191, 150, 99));
        tablaListadoUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre completo", "Tienda", "Usuario", "Contraseña", "Tipo", "Estado", "Fecha alta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListadoUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaListadoUsuarios.setGridColor(new java.awt.Color(191, 150, 99));
        tablaListadoUsuarios.setSelectionBackground(new java.awt.Color(191, 150, 99));
        tablaListadoUsuarios.setSelectionForeground(new java.awt.Color(191, 150, 99));
        tablaListadoUsuarios.setShowGrid(false);
        tablaListadoUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListadoUsuarios);
        if (tablaListadoUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaListadoUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablaListadoUsuarios.getColumnModel().getColumn(1).setPreferredWidth(120);
            tablaListadoUsuarios.getColumnModel().getColumn(2).setPreferredWidth(50);
            tablaListadoUsuarios.getColumnModel().getColumn(3).setPreferredWidth(50);
            tablaListadoUsuarios.getColumnModel().getColumn(4).setPreferredWidth(60);
            tablaListadoUsuarios.getColumnModel().getColumn(5).setPreferredWidth(40);
            tablaListadoUsuarios.getColumnModel().getColumn(6).setPreferredWidth(50);
            tablaListadoUsuarios.getColumnModel().getColumn(7).setPreferredWidth(60);
        }

        jPanel1.setBackground(new java.awt.Color(3, 32, 38));

        lblImprimirAdmin.setBackground(new java.awt.Color(9, 48, 64));
        lblImprimirAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblImprimirAdmin.setForeground(new java.awt.Color(191, 150, 99));
        lblImprimirAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUsuario1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario1.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario1)
                .addGap(6, 6, 6)
                .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario1)
                    .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        panelFinal.setBackground(new java.awt.Color(112, 137, 140));
        panelFinal.setOpaque(false);

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(154, 176, 179));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSistemaGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToolBar1.setBackground(new java.awt.Color(191, 150, 99));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(2, 2));
        jToolBar1.setMinimumSize(new java.awt.Dimension(2, 2));

        botonNuevo.setBackground(new java.awt.Color(191, 150, 99));
        botonNuevo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonNuevo.setText("Ir a Registrar Nuevo Usuario");
        botonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(3, 32, 38));
        botonVolver.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(191, 150, 99));
        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(3, 32, 38));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACION DE USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(191, 150, 99))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(191, 150, 99));

        lblUsuario2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario2.setText("ID EMPLEADO:");

        lblUsuario3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario3.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario3.setText("NOMBRE COMPLETO:");

        lblUsuario4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario4.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario4.setText("TIENDA:");

        lblUsuario5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario5.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario5.setText("USUARIO:");

        lblUsuario6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario6.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario6.setText("CONTRASEÑA:");

        lblUsuario7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario7.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario7.setText("TIPO:");

        lblUsuario8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario8.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario8.setText("ESTADO:");

        lblUsuario9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario9.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario9.setText("FECHA ALTA:");

        campoIdEmpleado.setEditable(false);
        campoIdEmpleado.setBackground(new java.awt.Color(3, 32, 38));
        campoIdEmpleado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoIdEmpleado.setForeground(new java.awt.Color(112, 137, 140));
        campoIdEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoIdEmpleado.setName("Codigo Producto"); // NOI18N

        campoNombreCompleto.setEditable(false);
        campoNombreCompleto.setBackground(new java.awt.Color(3, 32, 38));
        campoNombreCompleto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoNombreCompleto.setForeground(new java.awt.Color(112, 137, 140));
        campoNombreCompleto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoNombreCompleto.setName("Nombre Completo"); // NOI18N

        campoUsuario.setEditable(false);
        campoUsuario.setBackground(new java.awt.Color(3, 32, 38));
        campoUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(112, 137, 140));
        campoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoUsuario.setName("Usuario"); // NOI18N
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        comboTienda.setBackground(new java.awt.Color(3, 32, 38));
        comboTienda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboTienda.setForeground(new java.awt.Color(112, 137, 140));
        comboTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", " " }));
        comboTienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboTienda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTienda.setName("Tienda"); // NOI18N

        comboTipo.setBackground(new java.awt.Color(3, 32, 38));
        comboTipo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboTipo.setForeground(new java.awt.Color(112, 137, 140));
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTipo.setName("Tipo"); // NOI18N

        comboEstado.setBackground(new java.awt.Color(3, 32, 38));
        comboEstado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboEstado.setForeground(new java.awt.Color(112, 137, 140));
        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboEstado.setName("Estado"); // NOI18N

        campoFechaAlta.setEditable(false);
        campoFechaAlta.setBackground(new java.awt.Color(3, 32, 38));
        campoFechaAlta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoFechaAlta.setForeground(new java.awt.Color(112, 137, 140));
        campoFechaAlta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoFechaAlta.setName("Fecha de Alta"); // NOI18N
        campoFechaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaAltaActionPerformed(evt);
            }
        });

        campoPass.setEditable(false);
        campoPass.setBackground(new java.awt.Color(3, 32, 38));
        campoPass.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPass.setForeground(new java.awt.Color(112, 137, 140));
        campoPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPass.setName("Pass"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario7)
                            .addComponent(lblUsuario8)
                            .addComponent(lblUsuario9)
                            .addComponent(lblUsuario5)
                            .addComponent(lblUsuario4)
                            .addComponent(lblUsuario3)
                            .addComponent(lblUsuario2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFechaAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoPass)
                                    .addComponent(campoIdEmpleado)
                                    .addComponent(campoNombreCompleto)
                                    .addComponent(campoUsuario)
                                    .addComponent(comboTienda, 0, 252, Short.MAX_VALUE)
                                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsuario6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario2)
                    .addComponent(campoIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario3)
                    .addComponent(campoNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario4)
                    .addComponent(comboTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuario5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuario6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPass))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario7)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario8)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario9)
                    .addComponent(campoFechaAlta))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        botonEditarDatos.setBackground(new java.awt.Color(3, 32, 38));
        botonEditarDatos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonEditarDatos.setForeground(new java.awt.Color(191, 150, 99));
        botonEditarDatos.setText("Clic Para Activar el Panel y Editar");
        botonEditarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarDatosActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(3, 32, 38));
        botonGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(191, 150, 99));
        botonGuardar.setText("Guardar Edición de Usuario");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(411, 411, 411))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEditarDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonGuardar)
                                .addGap(29, 29, 29)
                                .addComponent(botonVolver)
                                .addGap(26, 26, 26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonVolver)
                            .addComponent(botonGuardar)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEditarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));

        menuArchivo.setText("Archivo");
        menuArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuArchivo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemCerrar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemCerrar.setText("Cerrar");
        itemCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCerrar);

        jMenuBar1.add(menuArchivo);

        menuAyuda.setText("Ayuda");
        menuAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAyuda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemAcercaDe.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        utilidades.Utilidades.mostrarAcercaDe(this);
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
    RegistrarUsuario rnu = new RegistrarUsuario(null, true); 
    rnu.setVisible(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoFechaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaAltaActionPerformed

    private void botonEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarDatosActionPerformed
        if (campoIdEmpleado.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "Selecciona un usuario de la tabla primero.", 
                "Sin selección", 
                JOptionPane.WARNING_MESSAGE);
        } else {
            
            activarEdicion();
        }
    }//GEN-LAST:event_botonEditarDatosActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        guardarUsuario();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void tablaListadoUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoUsuariosMouseClicked
        
        int fila = tablaListadoUsuarios.getSelectedRow();
        if (fila != -1) {
            
            // Rellenar campos de texto 
            campoIdEmpleado.setText(tablaListadoUsuarios.getValueAt(fila, 0).toString()); // 0=ID, 1=Nombre, 3=Usuario, 4=Pass, 7=Fecha
            campoNombreCompleto.setText(tablaListadoUsuarios.getValueAt(fila, 1).toString());
            
            // Los campos de Tienda y Tipo en la tabla están en las columnas 2, 5 y 6
            String tienda = tablaListadoUsuarios.getValueAt(fila, 2).toString();
            
            campoUsuario.setText(tablaListadoUsuarios.getValueAt(fila, 3).toString());
            campoPass.setText(tablaListadoUsuarios.getValueAt(fila, 4).toString());
            
            String tipo = tablaListadoUsuarios.getValueAt(fila, 5).toString();
            String estado = tablaListadoUsuarios.getValueAt(fila, 6).toString();
            
            // Fecha de alta - columna 7:
            if (tablaListadoUsuarios.getValueAt(fila, 7) != null) {
                
                campoFechaAlta.setText(tablaListadoUsuarios.getValueAt(fila, 7).toString());
            }

            // Seleccionamos los valores en los combos
            comboTienda.setSelectedItem(tienda);
            comboTipo.setSelectedItem(tipo);
            comboEstado.setSelectedItem(estado);
            
            desactivarEdicion(); // Bloqueamos por seguridad
        }
    }//GEN-LAST:event_tablaListadoUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VerListadoUsuarios dialog = new VerListadoUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditarDatos;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoFechaAlta;
    private javax.swing.JTextField campoIdEmpleado;
    private javax.swing.JTextField campoNombreCompleto;
    private javax.swing.JPasswordField campoPass;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboTienda;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblImprimirAdmin;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JLabel lblUsuario6;
    private javax.swing.JLabel lblUsuario7;
    private javax.swing.JLabel lblUsuario8;
    private javax.swing.JLabel lblUsuario9;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaListadoUsuarios;
    // End of variables declaration//GEN-END:variables


    
    
    /**
     * Valida y guarda los cambios de los 3 desplegables.
     */
    public void guardarUsuario() {
        if (campoIdEmpleado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario primero.", "Sin selección", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar combo seleccione
        if (Utilidades.compruebaComboNoSeleccionado(comboTienda)) {
            Utilidades.lanzaAlertaCombo(comboTienda);
            return;
            
        } else if (Utilidades.compruebaComboNoSeleccionado(comboTipo)) {
            Utilidades.lanzaAlertaCombo(comboTipo);
            return;
            
        } else if (Utilidades.compruebaComboNoSeleccionado(comboEstado)) {
            Utilidades.lanzaAlertaCombo(comboEstado);
            return;
        }

        // Rescatar datos
        String idUsuario = campoIdEmpleado.getText();
        String nuevaTienda = comboTienda.getSelectedItem().toString();
        String nuevoTipo = comboTipo.getSelectedItem().toString();
        String nuevoEstado = comboEstado.getSelectedItem().toString();

        if (ConsultasUsuarios.actualizarUsuarioRoles(idUsuario, nuevaTienda, nuevoTipo, nuevoEstado)) {
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
            
            ConsultasUsuarios.cargarListadoUsuarios((DefaultTableModel) tablaListadoUsuarios.getModel());
            
            desactivarEdicion();
            limpiarFormulario();
            
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar los datos del usuario.", "Error BBDD", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Limpia la pantalla.
     */
    public void limpiarFormulario() {
        campoIdEmpleado.setText("");
        campoNombreCompleto.setText("");
        campoUsuario.setText("");
        campoPass.setText("");
        campoFechaAlta.setText("");
        comboTienda.setSelectedIndex(0);
        comboTipo.setSelectedIndex(0);
        comboEstado.setSelectedIndex(0);
        desactivarEdicion();
    }
    
    
    /**
     * Carga todos los valores dinámicos en los 3 desplegables.
     */
    private void cargarCombos() {
        
        // Tienda: Desde su propia tabla
        comboTienda.removeAllItems();
        comboTienda.addItem("Seleccione");
        java.util.ArrayList<String> tiendas = bbdd.ConsultasTiendas.obtenerNombresTiendas();
        for (String t : tiendas) { comboTienda.addItem(t); }

        // Tipo: que es un ENUM:
        comboTipo.removeAllItems();
        comboTipo.addItem("Seleccione");
        java.util.ArrayList<String> tipos = bbdd.Conexion.obtenerValoresEnum("usuarios", "tipo");
        for (String t : tipos) { comboTipo.addItem(t); }

        // Estado: que es otro ENUM:
        comboEstado.removeAllItems();
        comboEstado.addItem("Seleccione");
        java.util.ArrayList<String> estados = bbdd.Conexion.obtenerValoresEnum("usuarios", "estado");
        for (String e : estados) { comboEstado.addItem(e); }
    }
    
    
    
    /**
     * Desactiva los 3 combos.
     */
    public void desactivarEdicion() {
        comboTienda.setEnabled(false);
        comboTipo.setEnabled(false);
        comboEstado.setEnabled(false);
    }

    /**
     * Activa los 3 combos para su edición.
     */
    public void activarEdicion() {
        
        comboTienda.setEnabled(true);
        comboTipo.setEnabled(true);
        comboEstado.setEnabled(true);
        
        JOptionPane.showMessageDialog(this, 
            "Ya puede modificar los campos Tienda, Tipo y Estado del usuario desde los menús desplegables.", 
            "Modo edición activado", 
            JOptionPane.INFORMATION_MESSAGE);
    }
  
}
