/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.vistasAdmin;

import bbdd.ConsultasProducto;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import utilidades.Utilidades;
import vistas.VentanaLogin;

/**
 * Ventana de listado de artículos.
 * Permite visualizar el catálogo y al seleccionar un artículo modificar exclusivamente su valor de Destacado: Sí / No a través de un Combo-box.
 * @author Jose y Patricia
 */
public class VerListadoDestacados extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerListadoDestacados.class.getName());

    /**
     * Constructor principal de la ventana.
     * Inicializa los componentes, aplica la identidad visual, carga la tabla y prepara los desplegables.
     * 
     */
    public VerListadoDestacados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Cargar tabla al abrir
        ConsultasProducto.ArticulosDestacadosAdmin((DefaultTableModel) tablaArticulosDestacados.getModel());
        
        Utilidades.disenoTablas(tablaArticulosDestacados);
        
        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);
        
        // Rescatar fecha y hora en la interfaz
        LocalDateTime fechaHora = LocalDateTime.now();
        lblRescataFechayHora.setText("Admin activo — "
                + fechaHora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));

        // Rescata Administrador:
        lblImprimirAdmin.setText(VentanaLogin.user);
        
        // Preparar Combo y campos:
        cargarComboDestacado();
        desactivarEdicion();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulosDestacados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblImprimirAdmin = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblUsuario2 = new javax.swing.JLabel();
        lblUsuario3 = new javax.swing.JLabel();
        lblUsuario4 = new javax.swing.JLabel();
        lblUsuario5 = new javax.swing.JLabel();
        lblUsuario6 = new javax.swing.JLabel();
        lblUsuario7 = new javax.swing.JLabel();
        lblUsuario8 = new javax.swing.JLabel();
        lblUsuario9 = new javax.swing.JLabel();
        lblUsuario10 = new javax.swing.JLabel();
        lblUsuario11 = new javax.swing.JLabel();
        campoCodProducto = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoPrecioCompra = new javax.swing.JTextField();
        campoPrecioVenta = new javax.swing.JTextField();
        campoStock = new javax.swing.JTextField();
        comboDestacado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        campoOrigen = new javax.swing.JTextField();
        campoOferta = new javax.swing.JTextField();
        campoCategoria = new javax.swing.JTextField();
        botonEditarArticuloDestacado = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA LISTADO DESTACADOS");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(3, 32, 38));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo.setText("Listado de articulos destacados");

        lblSubtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo.setText("Listado de artículos destacados");

        tablaArticulosDestacados.setBackground(new java.awt.Color(9, 48, 64));
        tablaArticulosDestacados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));
        tablaArticulosDestacados.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tablaArticulosDestacados.setForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosDestacados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "PVP", "Destacado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulosDestacados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaArticulosDestacados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaArticulosDestacados.setFillsViewportHeight(true);
        tablaArticulosDestacados.setGridColor(new java.awt.Color(191, 150, 99));
        tablaArticulosDestacados.setRowHeight(25);
        tablaArticulosDestacados.setSelectionBackground(new java.awt.Color(191, 150, 99));
        tablaArticulosDestacados.setSelectionForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosDestacados.setShowGrid(false);
        tablaArticulosDestacados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArticulosDestacadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaArticulosDestacados);
        if (tablaArticulosDestacados.getColumnModel().getColumnCount() > 0) {
            tablaArticulosDestacados.getColumnModel().getColumn(0).setResizable(false);
            tablaArticulosDestacados.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablaArticulosDestacados.getColumnModel().getColumn(1).setResizable(false);
            tablaArticulosDestacados.getColumnModel().getColumn(1).setPreferredWidth(150);
            tablaArticulosDestacados.getColumnModel().getColumn(2).setResizable(false);
            tablaArticulosDestacados.getColumnModel().getColumn(2).setPreferredWidth(150);
            tablaArticulosDestacados.getColumnModel().getColumn(3).setResizable(false);
            tablaArticulosDestacados.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(3, 32, 38));

        lblImprimirAdmin.setBackground(new java.awt.Color(9, 48, 64));
        lblImprimirAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblImprimirAdmin.setForeground(new java.awt.Color(191, 150, 99));
        lblImprimirAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUsuario1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario1.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario1)
                .addGap(6, 6, 6)
                .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario1)
                    .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        panelFinal.setBackground(new java.awt.Color(112, 137, 140));
        panelFinal.setOpaque(false);

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(154, 176, 179));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSistemaGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToolBar1.setBackground(new java.awt.Color(191, 150, 99));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(2, 2));
        jToolBar1.setMinimumSize(new java.awt.Dimension(2, 2));

        botonVolver.setBackground(new java.awt.Color(3, 32, 38));
        botonVolver.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(191, 150, 99));
        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(3, 32, 38));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACION DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(191, 150, 99))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(191, 150, 99));

        lblUsuario2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario2.setText("CODIGO PRODUCTO:");

        lblUsuario3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario3.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario3.setText("NOMBRE:");

        lblUsuario4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario4.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario4.setText("CATEGORIA:");

        lblUsuario5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario5.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario5.setText("DESCRIPCIÓN:");

        lblUsuario6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario6.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario6.setText("PRECIO COMPRA:");

        lblUsuario7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario7.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario7.setText("PRECIO VENTA:");

        lblUsuario8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario8.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario8.setText("STOCK:");

        lblUsuario9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario9.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario9.setText("ORIGEN:");

        lblUsuario10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario10.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario10.setText("DESTACADO:");

        lblUsuario11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario11.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario11.setText("OFERTA:");

        campoCodProducto.setEditable(false);
        campoCodProducto.setBackground(new java.awt.Color(3, 32, 38));
        campoCodProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoCodProducto.setForeground(new java.awt.Color(112, 137, 140));
        campoCodProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoCodProducto.setName("Codigo Producto"); // NOI18N

        campoNombre.setEditable(false);
        campoNombre.setBackground(new java.awt.Color(3, 32, 38));
        campoNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(112, 137, 140));
        campoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoNombre.setName("Nombre"); // NOI18N

        campoPrecioCompra.setEditable(false);
        campoPrecioCompra.setBackground(new java.awt.Color(3, 32, 38));
        campoPrecioCompra.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPrecioCompra.setForeground(new java.awt.Color(112, 137, 140));
        campoPrecioCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPrecioCompra.setName("Precio Compra"); // NOI18N

        campoPrecioVenta.setEditable(false);
        campoPrecioVenta.setBackground(new java.awt.Color(3, 32, 38));
        campoPrecioVenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPrecioVenta.setForeground(new java.awt.Color(112, 137, 140));
        campoPrecioVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPrecioVenta.setName("Precio Venta"); // NOI18N

        campoStock.setEditable(false);
        campoStock.setBackground(new java.awt.Color(3, 32, 38));
        campoStock.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoStock.setForeground(new java.awt.Color(112, 137, 140));
        campoStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoStock.setName("Denominación"); // NOI18N

        comboDestacado.setBackground(new java.awt.Color(3, 32, 38));
        comboDestacado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        comboDestacado.setForeground(new java.awt.Color(112, 137, 140));
        comboDestacado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboDestacado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        comboDestacado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboDestacado.setName("Destacado"); // NOI18N

        campoDescripcion.setEditable(false);
        campoDescripcion.setBackground(new java.awt.Color(3, 32, 38));
        campoDescripcion.setColumns(20);
        campoDescripcion.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoDescripcion.setForeground(new java.awt.Color(112, 137, 140));
        campoDescripcion.setLineWrap(true);
        campoDescripcion.setRows(5);
        campoDescripcion.setWrapStyleWord(true);
        campoDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoDescripcion.setName("Descripción"); // NOI18N
        jScrollPane2.setViewportView(campoDescripcion);

        campoOrigen.setEditable(false);
        campoOrigen.setBackground(new java.awt.Color(3, 32, 38));
        campoOrigen.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoOrigen.setForeground(new java.awt.Color(112, 137, 140));
        campoOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoOrigen.setName("Origen"); // NOI18N

        campoOferta.setEditable(false);
        campoOferta.setBackground(new java.awt.Color(3, 32, 38));
        campoOferta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoOferta.setForeground(new java.awt.Color(112, 137, 140));
        campoOferta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoOferta.setName("Oferta"); // NOI18N

        campoCategoria.setEditable(false);
        campoCategoria.setBackground(new java.awt.Color(3, 32, 38));
        campoCategoria.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoCategoria.setForeground(new java.awt.Color(112, 137, 140));
        campoCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoCategoria.setName("Categoría"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario6)
                    .addComponent(lblUsuario7)
                    .addComponent(lblUsuario8)
                    .addComponent(lblUsuario9)
                    .addComponent(lblUsuario10)
                    .addComponent(lblUsuario11)
                    .addComponent(lblUsuario5)
                    .addComponent(lblUsuario4)
                    .addComponent(lblUsuario3)
                    .addComponent(lblUsuario2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoCodProducto)
                            .addComponent(campoNombre)
                            .addComponent(campoPrecioVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoStock, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboDestacado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)))
                    .addComponent(campoOrigen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoOferta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario2)
                    .addComponent(campoCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario3)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario4)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario6)
                    .addComponent(campoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario7)
                    .addComponent(campoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario8)
                    .addComponent(campoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario9)
                    .addComponent(campoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario10)
                    .addComponent(comboDestacado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario11)
                    .addComponent(campoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        botonEditarArticuloDestacado.setBackground(new java.awt.Color(3, 32, 38));
        botonEditarArticuloDestacado.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonEditarArticuloDestacado.setForeground(new java.awt.Color(191, 150, 99));
        botonEditarArticuloDestacado.setText("Clic para Activar el Panel y Editar");
        botonEditarArticuloDestacado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditarArticuloDestacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarArticuloDestacadoActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(3, 32, 38));
        botonGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(191, 150, 99));
        botonGuardar.setText("Guardar Edición de Artículo Destacado");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditarArticuloDestacado, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(39, 39, 39)
                        .addComponent(botonVolver)
                        .addGap(47, 47, 47))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(botonEditarArticuloDestacado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVolver)
                    .addComponent(botonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));

        menuArchivo.setText("Archivo");
        menuArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuArchivo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemCerrar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemCerrar.setText("Cerrar");
        itemCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCerrar);

        jMenuBar1.add(menuArchivo);

        menuAyuda.setText("Ayuda");
        menuAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAyuda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemAcercaDe.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        utilidades.Utilidades.mostrarAcercaDe(this);
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonEditarArticuloDestacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarArticuloDestacadoActionPerformed
        
        if (campoCodProducto.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "Selecciona un artículo destacado de la tabla primero.", 
                "Sin selección", 
                JOptionPane.WARNING_MESSAGE);
        } else {
            activarEdicion();
        }
    }//GEN-LAST:event_botonEditarArticuloDestacadoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        guardarArticuloDestacado();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void tablaArticulosDestacadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArticulosDestacadosMouseClicked
       
        int fila = tablaArticulosDestacados.getSelectedRow();
        if (fila != -1) {
            
            String codigo = tablaArticulosDestacados.getValueAt(fila, 0).toString();
            Producto p = ConsultasProducto.rescatarProductoPorCodigo(codigo);
            
            if (p != null) {
                
                campoCodProducto.setText(p.getCodProducto());
                campoNombre.setText(p.getNombre());
                campoCategoria.setText(p.getCategoria());
                campoDescripcion.setText(p.getDescripcion());
                campoPrecioCompra.setText(String.valueOf(p.getPrecioCompra()));
                campoPrecioVenta.setText(String.valueOf(p.getPrecioVenta()));
                campoStock.setText(String.valueOf(p.getStock()));
                campoOrigen.setText(p.getOrigen());
                campoOferta.setText(p.getOferta());
                
                
                comboDestacado.setSelectedItem(p.getDestacado());
                
                // Bloquear edición por seguridad al cambiar de fila
                desactivarEdicion(); 
            } else {
                
                JOptionPane.showMessageDialog(this, "Error al rescatar el producto.");
            }
        }
    }//GEN-LAST:event_tablaArticulosDestacadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VerListadoDestacados dialog = new VerListadoDestacados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditarArticuloDestacado;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoCodProducto;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoOferta;
    private javax.swing.JTextField campoOrigen;
    private javax.swing.JTextField campoPrecioCompra;
    private javax.swing.JTextField campoPrecioVenta;
    private javax.swing.JTextField campoStock;
    private javax.swing.JComboBox<String> comboDestacado;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblImprimirAdmin;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario10;
    private javax.swing.JLabel lblUsuario11;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JLabel lblUsuario6;
    private javax.swing.JLabel lblUsuario7;
    private javax.swing.JLabel lblUsuario8;
    private javax.swing.JLabel lblUsuario9;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaArticulosDestacados;
    // End of variables declaration//GEN-END:variables


    
    /**
     * Guarda la selección del nuevo estado de Destacado en la base de datos.
     */
    public void guardarArticuloDestacado() {
        
        if (campoCodProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un artículo primero.", "Sin selección", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (Utilidades.compruebaComboNoSeleccionado(comboDestacado)) {
            Utilidades.lanzaAlertaCombo(comboDestacado);
            return;
        }
        
        // Nueva confirmación:
        String nombreArticuloDestacado = campoNombre.getText();
        String nuevoDestacado = comboDestacado.getSelectedItem().toString();
        
        int respuesta = JOptionPane.showConfirmDialog(
            this, 
            "¿Desea cambiar el estado de " + nombreArticuloDestacado + " a " + nuevoDestacado + "?", 
            "Confirmar Cambio", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta != JOptionPane.YES_OPTION) {
            return; // El usuario canceló, salimos del método
        }
       
        
        String codigo = campoCodProducto.getText();
        
        if (ConsultasProducto.actualizarDestacado(codigo, nuevoDestacado)) {
            
            JOptionPane.showMessageDialog(this, "Estado destacado actualizado correctamente.");
            
            ConsultasProducto.ArticulosDestacadosAdmin((DefaultTableModel) tablaArticulosDestacados.getModel());
            
            desactivarEdicion();
            
            limpiarFormulario();
            
        } else {
            
            JOptionPane.showMessageDialog(this, "Error al actualizar el estado.", "Error BBDD", JOptionPane.ERROR_MESSAGE);
        }
    }
    
  
    /**
     * Limpia todos los campos del formulario y restablece el estado de edición.
     */
    public void limpiarFormulario() {
        campoCodProducto.setText("");
        campoNombre.setText("");
        campoCategoria.setText("");
        campoDescripcion.setText("");
        campoPrecioCompra.setText("");
        campoPrecioVenta.setText("");
        campoStock.setText("");
        campoOrigen.setText("");
        campoOferta.setText("");
        comboDestacado.setSelectedIndex(0);
        desactivarEdicion();
    }
    
    
  
    /**
     * Carga dinámicamente los valores permitidos para el estado "Destacado" consultando la estructura ENUM - SI / NO, de la base de datos.
     */
    private void cargarComboDestacado() {
        
        comboDestacado.removeAllItems();
        comboDestacado.addItem("Seleccione");
        
        java.util.ArrayList<String> destacados = bbdd.Conexion.obtenerValoresEnum("producto", "destacado");
        for (String dest : destacados) {
            
            comboDestacado.addItem(dest);
        }
    }
    
    
    /**
     * Deshabilita el JComboBox de Destacado.
     */
    public void desactivarEdicion() {
        comboDestacado.setEnabled(false);
    }

    
    /**
     * Habilita el JComboBox de Destacado para permitir cambios.
     */
    public void activarEdicion() {
        comboDestacado.setEnabled(true);
        JOptionPane.showMessageDialog(this, 
            "Ya puede editar el estado de Destacado del artículo desde el menú desplegable.", 
            "Modo edición activado", 
            JOptionPane.INFORMATION_MESSAGE);
    }

}
