/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas.vistasAdmin;

import bbdd.ConsultasProducto;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import utilidades.Utilidades;
import vistas.VentanaLogin;

/**
 * Ventana de listado de artículos del administrador. Permite consultar la tabla
 * y al seleccionar un registro carga sus datos en el panel derecho. Los campos
 * solo son editables tras pulsar el botón "Editar Productos". Permite
 * consultar, editar únicamente Nombre y Descripción, y eliminar productos.
 *
 * @author Jose y Patricia.
 */
public class VerListadoArticulos extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerListadoArticulos.class.getName());

    /**
     * Constructor de la ventana de listado de artículos. Inicializa
     * componentes, carga datos y configura la UI.
     */
    public VerListadoArticulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);

        // Cargar tabla al abrir 
        ConsultasProducto.cargarListadoArticulos((DefaultTableModel) tablaListadoArticulos.getModel());

       Utilidades.disenoTablas(tablaListadoArticulos);

        // Bloquear panel derecho al abrir
        desactivarEdicionProducto();

        // Rescatar fecha y hora en la interfaz
        LocalDateTime fechaHora = LocalDateTime.now();
        lblRescataFechayHora.setText("Admin activo — "
                + fechaHora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));

        // Rescata Administrador:
        lblImprimirAdmin.setText(VentanaLogin.user);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoArticulos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblImprimirAdmin = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        botonVolver = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario2 = new javax.swing.JLabel();
        lblUsuario3 = new javax.swing.JLabel();
        lblUsuario4 = new javax.swing.JLabel();
        lblUsuario5 = new javax.swing.JLabel();
        lblUsuario6 = new javax.swing.JLabel();
        lblUsuario7 = new javax.swing.JLabel();
        lblUsuario8 = new javax.swing.JLabel();
        lblUsuario9 = new javax.swing.JLabel();
        lblUsuario10 = new javax.swing.JLabel();
        lblUsuario11 = new javax.swing.JLabel();
        campoCodProducto = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoPrecioCompra = new javax.swing.JTextField();
        campoPrecioVenta = new javax.swing.JTextField();
        campoStock = new javax.swing.JTextField();
        campoCategoria = new javax.swing.JTextField();
        campoOrigen = new javax.swing.JTextField();
        campoOferta = new javax.swing.JTextField();
        campoDestacado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        botonGuardar = new javax.swing.JButton();
        botonEditarProductos = new javax.swing.JButton();
        botoneEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA LISTADO ARTÍCULOS");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(3, 32, 38));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo.setText("Listado total de artículos ");

        lblSubtitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo.setText("Listado de articulos en la tienda");

        tablaListadoArticulos.setBackground(new java.awt.Color(9, 48, 64));
        tablaListadoArticulos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));
        tablaListadoArticulos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tablaListadoArticulos.setForeground(new java.awt.Color(191, 150, 99));
        tablaListadoArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "PVP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListadoArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaListadoArticulos.setGridColor(new java.awt.Color(191, 150, 99));
        tablaListadoArticulos.setSelectionBackground(new java.awt.Color(191, 150, 99));
        tablaListadoArticulos.setSelectionForeground(new java.awt.Color(191, 150, 99));
        tablaListadoArticulos.setShowGrid(false);
        tablaListadoArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListadoArticulos);
        if (tablaListadoArticulos.getColumnModel().getColumnCount() > 0) {
            tablaListadoArticulos.getColumnModel().getColumn(0).setResizable(false);
            tablaListadoArticulos.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablaListadoArticulos.getColumnModel().getColumn(1).setResizable(false);
            tablaListadoArticulos.getColumnModel().getColumn(2).setResizable(false);
            tablaListadoArticulos.getColumnModel().getColumn(3).setResizable(false);
            tablaListadoArticulos.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jPanel3.setBackground(new java.awt.Color(3, 32, 38));

        lblImprimirAdmin.setBackground(new java.awt.Color(9, 48, 64));
        lblImprimirAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblImprimirAdmin.setForeground(new java.awt.Color(191, 150, 99));
        lblImprimirAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUsuario1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario1.setText("Usuario:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario1)
                .addGap(6, 6, 6)
                .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario1)
                    .addComponent(lblImprimirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelFinal.setBackground(new java.awt.Color(112, 137, 140));
        panelFinal.setOpaque(false);

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(154, 176, 179));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSistemaGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToolBar1.setBackground(new java.awt.Color(191, 150, 99));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(2, 2));
        jToolBar1.setMinimumSize(new java.awt.Dimension(2, 2));

        botonVolver.setBackground(new java.awt.Color(3, 32, 38));
        botonVolver.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(191, 150, 99));
        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonActualizar.setBackground(new java.awt.Color(191, 150, 99));
        botonActualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonActualizar.setText("Ir a Registrar Nuevo Artículo");
        botonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(3, 32, 38));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACION DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), new java.awt.Color(191, 150, 99))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(191, 150, 99));
        jPanel1.setEnabled(false);

        lblUsuario2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario2.setText("CODIGO PRODUCTO:");

        lblUsuario3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario3.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario3.setText("NOMBRE:");

        lblUsuario4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario4.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario4.setText("CATEGORIA:");

        lblUsuario5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario5.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario5.setText("DESCRIPCIÓN:");

        lblUsuario6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario6.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario6.setText("PRECIO COMPRA:");

        lblUsuario7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario7.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario7.setText("PRECIO VENTA:");

        lblUsuario8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario8.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario8.setText("STOCK:");

        lblUsuario9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario9.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario9.setText("ORIGEN:");

        lblUsuario10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario10.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario10.setText("DESTACADO:");

        lblUsuario11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario11.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario11.setText("OFERTA:");

        campoCodProducto.setEditable(false);
        campoCodProducto.setBackground(new java.awt.Color(3, 32, 38));
        campoCodProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoCodProducto.setForeground(new java.awt.Color(112, 137, 140));
        campoCodProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoCodProducto.setName("Código Producto"); // NOI18N

        campoNombre.setBackground(new java.awt.Color(3, 32, 38));
        campoNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(112, 137, 140));
        campoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoNombre.setName("Nombre"); // NOI18N

        campoPrecioCompra.setEditable(false);
        campoPrecioCompra.setBackground(new java.awt.Color(3, 32, 38));
        campoPrecioCompra.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPrecioCompra.setForeground(new java.awt.Color(112, 137, 140));
        campoPrecioCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPrecioCompra.setName("Precio Compra"); // NOI18N

        campoPrecioVenta.setEditable(false);
        campoPrecioVenta.setBackground(new java.awt.Color(3, 32, 38));
        campoPrecioVenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoPrecioVenta.setForeground(new java.awt.Color(112, 137, 140));
        campoPrecioVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoPrecioVenta.setName("Precio Venta"); // NOI18N

        campoStock.setEditable(false);
        campoStock.setBackground(new java.awt.Color(3, 32, 38));
        campoStock.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoStock.setForeground(new java.awt.Color(112, 137, 140));
        campoStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoStock.setName("Stock"); // NOI18N

        campoCategoria.setEditable(false);
        campoCategoria.setBackground(new java.awt.Color(3, 32, 38));
        campoCategoria.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoCategoria.setForeground(new java.awt.Color(112, 137, 140));
        campoCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoCategoria.setName("Categoría"); // NOI18N

        campoOrigen.setEditable(false);
        campoOrigen.setBackground(new java.awt.Color(3, 32, 38));
        campoOrigen.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoOrigen.setForeground(new java.awt.Color(112, 137, 140));
        campoOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoOrigen.setName("Origen"); // NOI18N

        campoOferta.setEditable(false);
        campoOferta.setBackground(new java.awt.Color(3, 32, 38));
        campoOferta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoOferta.setForeground(new java.awt.Color(112, 137, 140));
        campoOferta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoOferta.setName("Oferta"); // NOI18N

        campoDestacado.setEditable(false);
        campoDestacado.setBackground(new java.awt.Color(3, 32, 38));
        campoDestacado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoDestacado.setForeground(new java.awt.Color(112, 137, 140));
        campoDestacado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 137, 140)));
        campoDestacado.setName("Destacado"); // NOI18N

        campoDescripcion.setBackground(new java.awt.Color(3, 32, 38));
        campoDescripcion.setColumns(20);
        campoDescripcion.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        campoDescripcion.setForeground(new java.awt.Color(112, 137, 140));
        campoDescripcion.setLineWrap(true);
        campoDescripcion.setRows(5);
        campoDescripcion.setWrapStyleWord(true);
        campoDescripcion.setAutoscrolls(false);
        campoDescripcion.setName("Descripción"); // NOI18N
        jScrollPane2.setViewportView(campoDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario6)
                    .addComponent(lblUsuario7)
                    .addComponent(lblUsuario8)
                    .addComponent(lblUsuario9)
                    .addComponent(lblUsuario10)
                    .addComponent(lblUsuario11)
                    .addComponent(lblUsuario5)
                    .addComponent(lblUsuario4)
                    .addComponent(lblUsuario3)
                    .addComponent(lblUsuario2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoDestacado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoNombre)
                    .addComponent(campoPrecioCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoPrecioVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoStock, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoOrigen)
                    .addComponent(campoOferta)
                    .addComponent(campoCodProducto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario2)
                    .addComponent(campoCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario4)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario6)
                    .addComponent(campoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario7)
                    .addComponent(campoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario8)
                    .addComponent(campoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario9)
                    .addComponent(campoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario10)
                    .addComponent(campoDestacado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario11)
                    .addComponent(campoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        botonGuardar.setBackground(new java.awt.Color(3, 32, 38));
        botonGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(191, 150, 99));
        botonGuardar.setText("Guardar edición de producto");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonEditarProductos.setBackground(new java.awt.Color(3, 32, 38));
        botonEditarProductos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botonEditarProductos.setForeground(new java.awt.Color(191, 150, 99));
        botonEditarProductos.setText("Clic para Activar el panel y Editar productos");
        botonEditarProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarProductosActionPerformed(evt);
            }
        });

        botoneEliminar.setBackground(new java.awt.Color(3, 32, 38));
        botoneEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        botoneEliminar.setForeground(new java.awt.Color(191, 150, 99));
        botoneEliminar.setText("Eliminar producto");
        botoneEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoneEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(337, Short.MAX_VALUE)
                        .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoneEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVolver)
                .addGap(14, 14, 14))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(205, Short.MAX_VALUE)
                        .addComponent(botonEditarProductos)
                        .addGap(37, 37, 37))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(botonEditarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolver)
                    .addComponent(botoneEliminar)
                    .addComponent(botonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));

        menuArchivo.setText("Archivo");
        menuArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuArchivo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemCerrar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemCerrar.setText("Cerrar");
        itemCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(itemCerrar);

        jMenuBar1.add(menuArchivo);

        menuAyuda.setText("Ayuda");
        menuAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAyuda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemAcercaDe.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        utilidades.Utilidades.mostrarAcercaDe(this);
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        RegistrarArticulo ra = new RegistrarArticulo(null, true);
        ra.setVisible(true);
        // Cuando se cierre la ventana de registro, recargamos la tabla por si hay datos nuevos
        ConsultasProducto.cargarListadoArticulos((DefaultTableModel) tablaListadoArticulos.getModel());
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        guardarArticulo();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonEditarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarProductosActionPerformed

        if (campoCodProducto.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Selecciona un artículo de la tabla primero.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE);
        } else {

            activarEdicionProducto();
        }


    }//GEN-LAST:event_botonEditarProductosActionPerformed

    private void botoneEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneEliminarActionPerformed

        if (campoCodProducto.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Selecciona un artículo de la tabla primero.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE);

            return;
        }

        //Confirmación:
        int confirmar = JOptionPane.showConfirmDialog(this,
                "¿Seguro que quieres eliminar el artículo " + campoNombre.getText() + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmar == JOptionPane.YES_OPTION) {

            if (ConsultasProducto.eliminarProducto(campoCodProducto.getText())) {
                JOptionPane.showMessageDialog(this, "Artículo eliminado correctamente.");
                ConsultasProducto.cargarListadoArticulos((DefaultTableModel) tablaListadoArticulos.getModel());
                limpiarFormularioVerListadoArticulos();
            }
        }


    }//GEN-LAST:event_botoneEliminarActionPerformed

    private void tablaListadoArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoArticulosMouseClicked

        int fila = tablaListadoArticulos.getSelectedRow();

        if (fila != -1) {

            String codigo = tablaListadoArticulos.getValueAt(fila, 0).toString();
            Producto p = ConsultasProducto.rescatarProductoPorCodigo(codigo);

            if (p != null) {

                campoCodProducto.setText(p.getCodProducto());
                campoNombre.setText(p.getNombre());
                campoCategoria.setText(p.getCategoria());
                campoDescripcion.setText(p.getDescripcion());
                campoPrecioCompra.setText(String.valueOf(p.getPrecioCompra()));
                campoPrecioVenta.setText(String.valueOf(p.getPrecioVenta()));
                campoStock.setText(String.valueOf(p.getStock()));
                campoOrigen.setText(p.getOrigen());
                campoDestacado.setText(p.getDestacado());
                campoOferta.setText(p.getOferta());

                // Por si cambiamos de fila, volvemos a bloquear la edición por seguridad
                desactivarEdicionProducto();
            } else {

                JOptionPane.showMessageDialog(this, "Error al rescatar el producto de la base de datos.");
            }
        }

    }//GEN-LAST:event_tablaListadoArticulosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VerListadoArticulos dialog = new VerListadoArticulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEditarProductos;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton botoneEliminar;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoCodProducto;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoDestacado;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoOferta;
    private javax.swing.JTextField campoOrigen;
    private javax.swing.JTextField campoPrecioCompra;
    private javax.swing.JTextField campoPrecioVenta;
    private javax.swing.JTextField campoStock;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblImprimirAdmin;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario10;
    private javax.swing.JLabel lblUsuario11;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JLabel lblUsuario6;
    private javax.swing.JLabel lblUsuario7;
    private javax.swing.JLabel lblUsuario8;
    private javax.swing.JLabel lblUsuario9;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaListadoArticulos;
    // End of variables declaration//GEN-END:variables

    /**
     * Guarda los cambios de nombre y descripción del producto seleccionado.
     * Solo valida nombre y descripción ya que son los únicos campos editables
     * requeridos. Si la actualización es correcta recarga la tabla y bloquea
     * los campos.
     */
    public void guardarArticulo() {

        if (campoCodProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un artículo primero.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE);

        } else if (Utilidades.compruebaCampoVacio(campoNombre)) {
            Utilidades.lanzaAlertaVacio(campoNombre);

        } else if (campoDescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "La descripción no puede estar vacía.",
                    "Campo vacío",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            
            // Nueva Confirmación
            String nombreArticuloListado = campoNombre.getText();
            int respuesta = JOptionPane.showConfirmDialog(
                    this, 
                    "¿Está seguro de que desea actualizar los datos de " + nombreArticuloListado + "?", 
                    "Confirmar actualización de producto", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE
            );

            
            if (respuesta != JOptionPane.YES_OPTION) {
                return;
            }

            if (ConsultasProducto.actualizarProducto(
                    campoCodProducto.getText(),
                    campoNombre.getText(),
                    campoDescripcion.getText())) {

                JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");

                // Recargar tabla
                ConsultasProducto.cargarListadoArticulos((DefaultTableModel) tablaListadoArticulos.getModel());

                desactivarEdicionProducto();
                limpiarFormularioVerListadoArticulos();
            } else {

                JOptionPane.showMessageDialog(this, "Error al actualizar el producto.");
            }
        }
    }

    /**
     * Limpia todos los campos del formulario de registro de artículo.
     */
    public void limpiarFormularioVerListadoArticulos() {

        campoCodProducto.setText("");
        campoNombre.setText("");
        campoCategoria.setText("");
        campoDescripcion.setText("");
        campoPrecioCompra.setText("");
        campoPrecioVenta.setText("");
        campoStock.setText("");
        campoOrigen.setText("");
        campoDestacado.setText("");
        campoOferta.setText("");
        desactivarEdicionProducto();
    }

    /**
     * Desactiva la edición de nombre y descripción del panel derecho. Se llama
     * al abrir la ventana, tras guardar y tras limpiar.
     */
    public void desactivarEdicionProducto() {
        campoNombre.setEditable(false);
        campoDescripcion.setEditable(false);
    }

    /**
     * Activa la edición de nombre y descripción del producto seleccionado. Se
     * llama únicamente al pulsar el botón Editar Producto con un producto
     * seleccionado. Manda un aviso informativo al clicar sobre el botón.
     */
    public void activarEdicionProducto() {
        campoNombre.setEditable(true);
        campoDescripcion.setEditable(true);

        JOptionPane.showMessageDialog(this,
                "Ya puede editar los campos Nombre y Descripción.",
                "Modo edición activado",
                JOptionPane.INFORMATION_MESSAGE);
    }

} // Final

