/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.vistasUser;

import bbdd.ConsultasProducto;
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;
import utilidades.Utilidades;

import vistas.VentanaLogin;
import vistas.vistasAdmin.VerListadoArticulos;

/**
 *
 * @author Jose y Patricia
 */
public class VentanaUser extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaUser.class.getName());

    /**
     * Creates new form VentanaUser
     */
    public VentanaUser() {
        initComponents();
        
        // Llamamos al Single Musical de JP Ferretería - Single Uno
        utilidades.Utilidades.reproducir("SingleFerreteriaUno.wav");
        

        // Establecer icono: LogoIcono_JP
        utilidades.Utilidades.establecerIcono(this);

        // Rescatar fecha y hora en la interfaz
        LocalDateTime fechaHora = LocalDateTime.now();
        lblRescataFechayHora.setText("Usuario activo — "
                + fechaHora.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));

        // Cargar tabla 3 últimos artículos 
        ConsultasProducto.ultimos3Articulos((DefaultTableModel) tablaArticulosRegistrados.getModel());
        
        Utilidades.disenoTablas(tablaArticulosRegistrados);
        
        // Rescata Usuario:
        lblImprimirUsuario.setText(VentanaLogin.user);
        
        // DisenoUtil.aplicarEstiloRedondeado(lbl, 20); 
        lblRescatarArticulosDisponibles.setText(String.valueOf(ConsultasProducto.rescataArticulosDisponibles()));
        lblRescatarEnOferta.setText(String.valueOf(ConsultasProducto.rescataArticulosOferta()));
        lblRescatarDestacados.setText(String.valueOf(ConsultasProducto.rescataArticulosDestacados()));
        

        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal4 = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        lblSubtitulo4 = new javax.swing.JLabel();
        panelLogo4 = new javax.swing.JPanel();
        lblNombre4 = new javax.swing.JLabel();
        lblLogo4 = new javax.swing.JLabel();
        panelUserSidebar = new javax.swing.JPanel();
        botonVerArticulosUser = new javax.swing.JButton();
        botonVerDestacadosUser = new javax.swing.JButton();
        botonVerOfertasUser = new javax.swing.JButton();
        botonVerMiCuentaUser = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        lblAcceso = new javax.swing.JLabel();
        panelFinal = new javax.swing.JPanel();
        lblSistemaGestion = new javax.swing.JLabel();
        lblRescataFechayHora = new javax.swing.JLabel();
        panelRescatarLabels = new javax.swing.JPanel();
        lblRescatarArticulosDisponibles = new javax.swing.JLabel();
        lblRescatarEnOferta = new javax.swing.JLabel();
        lblRescatarDestacados = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulosRegistrados = new javax.swing.JTable();
        lblSubtitulo5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImprimirUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemVerArticulos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemVerDestacados = new javax.swing.JMenuItem();
        itemVerOfertas = new javax.swing.JMenu();
        itemOfertas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemVerMicuenta = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA PRINCIPAL USUARIO");
        setResizable(false);

        panelPrincipal4.setBackground(new java.awt.Color(3, 32, 38));
        panelPrincipal4.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal4.setPreferredSize(new java.awt.Dimension(1000, 600));
        panelPrincipal4.setLayout(new java.awt.GridBagLayout());

        lblTitulo4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(191, 150, 99));
        lblTitulo4.setText("Bienvenido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 8, 0, 0);
        panelPrincipal4.add(lblTitulo4, gridBagConstraints);

        lblSubtitulo4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo4.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo4.setText("Consulta de productos y tu cuenta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 8, 0, 0);
        panelPrincipal4.add(lblSubtitulo4, gridBagConstraints);

        panelLogo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 3));
        panelLogo4.setOpaque(false);

        lblNombre4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblNombre4.setForeground(new java.awt.Color(191, 150, 99));
        lblNombre4.setText("Ferretería JP Fusión");

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoEmpresaPequeño.jpg"))); // NOI18N

        javax.swing.GroupLayout panelLogo4Layout = new javax.swing.GroupLayout(panelLogo4);
        panelLogo4.setLayout(panelLogo4Layout);
        panelLogo4Layout.setHorizontalGroup(
            panelLogo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogo4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogo4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo4)
                .addGap(43, 43, 43))
        );
        panelLogo4Layout.setVerticalGroup(
            panelLogo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogo4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLogo4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 0);
        panelPrincipal4.add(panelLogo4, gridBagConstraints);

        panelUserSidebar.setOpaque(false);

        botonVerArticulosUser.setBackground(new java.awt.Color(9, 48, 64));
        botonVerArticulosUser.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerArticulosUser.setForeground(new java.awt.Color(191, 150, 99));
        botonVerArticulosUser.setText("Ver Artículos");
        botonVerArticulosUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerArticulosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerArticulosUserActionPerformed(evt);
            }
        });

        botonVerDestacadosUser.setBackground(new java.awt.Color(9, 48, 64));
        botonVerDestacadosUser.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerDestacadosUser.setForeground(new java.awt.Color(191, 150, 99));
        botonVerDestacadosUser.setText("Ver Destacados");
        botonVerDestacadosUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerDestacadosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerDestacadosUserActionPerformed(evt);
            }
        });

        botonVerOfertasUser.setBackground(new java.awt.Color(9, 48, 64));
        botonVerOfertasUser.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerOfertasUser.setForeground(new java.awt.Color(191, 150, 99));
        botonVerOfertasUser.setText("Ver Ofertas");
        botonVerOfertasUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerOfertasUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerOfertasUserActionPerformed(evt);
            }
        });

        botonVerMiCuentaUser.setBackground(new java.awt.Color(9, 48, 64));
        botonVerMiCuentaUser.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonVerMiCuentaUser.setForeground(new java.awt.Color(191, 150, 99));
        botonVerMiCuentaUser.setText("Mi Cuenta");
        botonVerMiCuentaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerMiCuentaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMiCuentaUserActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(191, 150, 99));
        botonSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        botonSalir.setText("Salir del sistema");
        botonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUserSidebarLayout = new javax.swing.GroupLayout(panelUserSidebar);
        panelUserSidebar.setLayout(panelUserSidebarLayout);
        panelUserSidebarLayout.setHorizontalGroup(
            panelUserSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserSidebarLayout.createSequentialGroup()
                .addGroup(panelUserSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserSidebarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelUserSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonVerArticulosUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVerDestacadosUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVerOfertasUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVerMiCuentaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelUserSidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelUserSidebarLayout.setVerticalGroup(
            panelUserSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserSidebarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(botonVerArticulosUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVerDestacadosUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVerOfertasUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVerMiCuentaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = -65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        panelPrincipal4.add(panelUserSidebar, gridBagConstraints);

        lblAcceso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblAcceso.setForeground(new java.awt.Color(112, 137, 140));
        lblAcceso.setText("ACCESO RÁPIDO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 56, 0, 0);
        panelPrincipal4.add(lblAcceso, gridBagConstraints);

        panelFinal.setBackground(new java.awt.Color(112, 137, 140));
        panelFinal.setOpaque(false);

        lblSistemaGestion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSistemaGestion.setForeground(new java.awt.Color(191, 150, 99));
        lblSistemaGestion.setText("Sistema de gestión Ferretería JP Fusión");

        lblRescataFechayHora.setBackground(new java.awt.Color(154, 176, 179));
        lblRescataFechayHora.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblRescataFechayHora.setForeground(new java.awt.Color(191, 150, 99));

        javax.swing.GroupLayout panelFinalLayout = new javax.swing.GroupLayout(panelFinal);
        panelFinal.setLayout(panelFinalLayout);
        panelFinalLayout.setHorizontalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistemaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFinalLayout.setVerticalGroup(
            panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSistemaGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescataFechayHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 136, 6, 6);
        panelPrincipal4.add(panelFinal, gridBagConstraints);

        panelRescatarLabels.setBackground(new java.awt.Color(3, 32, 38));
        panelRescatarLabels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));

        lblRescatarArticulosDisponibles.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarArticulosDisponibles.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRescatarArticulosDisponibles.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarArticulosDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarArticulosDisponibles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarArticulosDisponibles.setOpaque(true);

        lblRescatarEnOferta.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarEnOferta.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRescatarEnOferta.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarEnOferta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarEnOferta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarEnOferta.setOpaque(true);

        lblRescatarDestacados.setBackground(new java.awt.Color(9, 48, 64));
        lblRescatarDestacados.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRescatarDestacados.setForeground(new java.awt.Color(191, 150, 99));
        lblRescatarDestacados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRescatarDestacados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 2));
        lblRescatarDestacados.setOpaque(true);

        lbl1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(191, 150, 99));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Artículos Disponibles");

        lbl3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(191, 150, 99));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Articulos destacados");

        lbl2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(191, 150, 99));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Articulos en oferta");

        javax.swing.GroupLayout panelRescatarLabelsLayout = new javax.swing.GroupLayout(panelRescatarLabels);
        panelRescatarLabels.setLayout(panelRescatarLabelsLayout);
        panelRescatarLabelsLayout.setHorizontalGroup(
            panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRescatarLabelsLayout.createSequentialGroup()
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRescatarLabelsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRescatarLabelsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRescatarArticulosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRescatarEnOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRescatarDestacados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelRescatarLabelsLayout.setVerticalGroup(
            panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRescatarLabelsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lbl3)
                    .addComponent(lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRescatarLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRescatarArticulosDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(lblRescatarEnOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRescatarDestacados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = -57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 62, 0, 0);
        panelPrincipal4.add(panelRescatarLabels, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(3, 32, 38));

        tablaArticulosRegistrados.setBackground(new java.awt.Color(9, 48, 64));
        tablaArticulosRegistrados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(191, 150, 99), 4, true));
        tablaArticulosRegistrados.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        tablaArticulosRegistrados.setForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "Stock", "Precio venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulosRegistrados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaArticulosRegistrados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaArticulosRegistrados.setFillsViewportHeight(true);
        tablaArticulosRegistrados.setGridColor(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setRowHeight(50);
        tablaArticulosRegistrados.setSelectionBackground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setSelectionForeground(new java.awt.Color(191, 150, 99));
        tablaArticulosRegistrados.setShowGrid(false);
        tablaArticulosRegistrados.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tablaArticulosRegistrados);
        if (tablaArticulosRegistrados.getColumnModel().getColumnCount() > 0) {
            tablaArticulosRegistrados.getColumnModel().getColumn(0).setResizable(false);
            tablaArticulosRegistrados.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaArticulosRegistrados.getColumnModel().getColumn(1).setResizable(false);
            tablaArticulosRegistrados.getColumnModel().getColumn(1).setPreferredWidth(150);
            tablaArticulosRegistrados.getColumnModel().getColumn(2).setResizable(false);
            tablaArticulosRegistrados.getColumnModel().getColumn(2).setPreferredWidth(150);
            tablaArticulosRegistrados.getColumnModel().getColumn(3).setResizable(false);
            tablaArticulosRegistrados.getColumnModel().getColumn(4).setResizable(false);
        }

        lblSubtitulo5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblSubtitulo5.setForeground(new java.awt.Color(112, 137, 140));
        lblSubtitulo5.setText("3 ÚLTIMOS ARTICULOS AÑADIDOS RECIENTEMENTE A LA TIENDA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblSubtitulo5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lblSubtitulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        panelPrincipal4.add(jPanel2, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(3, 32, 38));

        lblImprimirUsuario.setBackground(new java.awt.Color(9, 48, 64));
        lblImprimirUsuario.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblImprimirUsuario.setForeground(new java.awt.Color(191, 150, 99));
        lblImprimirUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(191, 150, 99));
        lblUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(6, 6, 6)
                .addComponent(lblImprimirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblImprimirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 6);
        panelPrincipal4.add(jPanel1, gridBagConstraints);

        jMenuBar1.setBackground(new java.awt.Color(10, 49, 64));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 150, 99), 4));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(10, 49, 64));
        jMenu1.setForeground(new java.awt.Color(10, 49, 64));
        jMenu1.setText("Artículos");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemVerArticulos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerArticulos.setText("Ver Artículos");
        itemVerArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerArticulosActionPerformed(evt);
            }
        });
        jMenu1.add(itemVerArticulos);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(10, 49, 64));
        jMenu2.setForeground(new java.awt.Color(10, 49, 64));
        jMenu2.setText("Destacados");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemVerDestacados.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerDestacados.setText("Ver Destacados");
        itemVerDestacados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerDestacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerDestacadosActionPerformed(evt);
            }
        });
        jMenu2.add(itemVerDestacados);

        jMenuBar1.add(jMenu2);

        itemVerOfertas.setBackground(new java.awt.Color(10, 49, 64));
        itemVerOfertas.setForeground(new java.awt.Color(10, 49, 64));
        itemVerOfertas.setText("Ofertas");
        itemVerOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerOfertas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemOfertas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemOfertas.setText("Ver Ofertas");
        itemOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOfertasActionPerformed(evt);
            }
        });
        itemVerOfertas.add(itemOfertas);

        jMenuBar1.add(itemVerOfertas);

        jMenu4.setBackground(new java.awt.Color(10, 49, 64));
        jMenu4.setForeground(new java.awt.Color(10, 49, 64));
        jMenu4.setText("Mi Cuenta");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemVerMicuenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemVerMicuenta.setText("Ver Mi Cuenta");
        itemVerMicuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVerMicuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerMicuentaActionPerformed(evt);
            }
        });
        jMenu4.add(itemVerMicuenta);

        jMenuBar1.add(jMenu4);

        menuAyuda.setBackground(new java.awt.Color(10, 49, 64));
        menuAyuda.setForeground(new java.awt.Color(10, 49, 64));
        menuAyuda.setText("Ayuda");
        menuAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAyuda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        itemAcercaDe.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal4, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal4, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        utilidades.Utilidades.salirAplicacion(this);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonVerMiCuentaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMiCuentaUserActionPerformed
        VerDatosCuenta vdatcuent = new VerDatosCuenta(this, true);
        vdatcuent.setVisible(true);
    }//GEN-LAST:event_botonVerMiCuentaUserActionPerformed

    private void botonVerOfertasUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerOfertasUserActionPerformed
        VerArticuloOferta vartof = new VerArticuloOferta(this, true);
        vartof.setVisible(true);
    }//GEN-LAST:event_botonVerOfertasUserActionPerformed

    private void botonVerDestacadosUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerDestacadosUserActionPerformed
        VerArticuloDestacado vartdes = new VerArticuloDestacado(this, true);
        vartdes.setVisible(true);
    }//GEN-LAST:event_botonVerDestacadosUserActionPerformed

    private void botonVerArticulosUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerArticulosUserActionPerformed
        VerListadoArticulo vlart = new VerListadoArticulo(this, true);
        vlart.setVisible(true);
    }//GEN-LAST:event_botonVerArticulosUserActionPerformed

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        utilidades.Utilidades.mostrarAcercaDe(this);
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void itemVerArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerArticulosActionPerformed
        VerListadoArticulo vlart = new VerListadoArticulo(this, true);
        vlart.setVisible(true);
    }//GEN-LAST:event_itemVerArticulosActionPerformed

    private void itemVerDestacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerDestacadosActionPerformed
        VerArticuloDestacado vartdes = new VerArticuloDestacado(this, true);
        vartdes.setVisible(true);
    }//GEN-LAST:event_itemVerDestacadosActionPerformed

    private void itemOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOfertasActionPerformed
        VerArticuloOferta vartof = new VerArticuloOferta(this, true);
        vartof.setVisible(true);
    }//GEN-LAST:event_itemOfertasActionPerformed

    private void itemVerMicuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerMicuentaActionPerformed
        VerDatosCuenta vdatcuent = new VerDatosCuenta(this, true);
        vdatcuent.setVisible(true);
    }//GEN-LAST:event_itemVerMicuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVerArticulosUser;
    private javax.swing.JButton botonVerDestacadosUser;
    private javax.swing.JButton botonVerMiCuentaUser;
    private javax.swing.JButton botonVerOfertasUser;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemOfertas;
    private javax.swing.JMenuItem itemVerArticulos;
    private javax.swing.JMenuItem itemVerDestacados;
    private javax.swing.JMenuItem itemVerMicuenta;
    private javax.swing.JMenu itemVerOfertas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblAcceso;
    private javax.swing.JLabel lblImprimirUsuario;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblRescataFechayHora;
    private javax.swing.JLabel lblRescatarArticulosDisponibles;
    private javax.swing.JLabel lblRescatarDestacados;
    private javax.swing.JLabel lblRescatarEnOferta;
    private javax.swing.JLabel lblSistemaGestion;
    private javax.swing.JLabel lblSubtitulo4;
    private javax.swing.JLabel lblSubtitulo5;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JPanel panelFinal;
    private javax.swing.JPanel panelLogo4;
    private javax.swing.JPanel panelPrincipal4;
    private javax.swing.JPanel panelRescatarLabels;
    private javax.swing.JPanel panelUserSidebar;
    private javax.swing.JTable tablaArticulosRegistrados;
    // End of variables declaration//GEN-END:variables

}
